### ISSUE TITLE
Long @mention names cause horizontal scrollbar in sidebar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud-libraries/nextcloud-vue#1085]
(Not sure if this is an issue in Talk or in the Vue components, please move if it’s in the wrong place. :)

Long names overflow the name container in the chat list, cc @ma12-co @danxuliu:
![sidebar long names and new message input position](https://user-images.githubusercontent.com/925062/71569882-aa955b80-2b04-11ea-8b4c-59fc38478e40.png)

**Comment by jancborchardt** [comment]
Now the reverse sort of happens – they don’t overflow the name container, but the sidebar container itself:

![mentions of long names cause horizontal scrollbar](https://user-images.githubusercontent.com/925062/81418737-70d8ff00-914d-11ea-8a0e-dfda0ce5c0c4.png)
![mentions of long names cause scrollbar](https://user-images.githubusercontent.com/925062/81418735-70406880-914d-11ea-898a-30537e4a25a6.png)

**Comment by skjnldsv** [comment]
Is it from the components @ma12-co ?

**Comment by ma12-co** [comment]
Not sure, will look into this soon

**Comment by marcoambrosini** [comment]
no longer an issue
