### ISSUE TITLE
emoji picker shows elongated highlight in Talk

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud-libraries/nextcloud-vue#1343]
Screenshot:
![Screenshot_20200825_092017](https://user-images.githubusercontent.com/551757/91145639-117c0c00-e6b6-11ea-8e88-6b63e84696f7.png)
Looking at the CSS inspector, it is due to this:
```
.emoji-mart-search-results {
￼    height: 250px;
```
 on the container with the results, which has these classes:
`emoji-mart-search-results emoji-mart-category`

**Comment by skjnldsv** [comment]
labels please @jospoortvliet :)

**Comment by AndyScherzinger** [comment]
From what I understood from @tobiasKaminsky , according to @nickvergessen this should be easy to fix with a lib update.

**Comment by nickvergessen** [comment]
Yeah was fixed with https://github.com/nextcloud/nextcloud-vue/pull/2370

so just missing the release or backport to a maintenance release and then an update in all apps

**Comment by jancborchardt** [comment]
Closing since it was fixed as mentioned.
