### ISSUE TITLE
AppSettingsDialog content can not be scrolled in Firefox

### ISSUE THREAD

**Issue by danxuliu** [nextcloud-libraries/nextcloud-vue#1506]
- Open the [AppSettingsDialog component documentation](https://nextcloud-vue-components.netlify.app/#/Components/AppSettingsDialog)* in Firefox
- Add tens of `<div>Some example content</div>` to the two `AppSettingsSection` (so the content is too large and a vertical scroll bar is shown once the AppSettingsDialog is opened)
- Show the settings
- Try to scroll with the arrow keys (I could not test with the mouse wheel. It broke. Again :angry:)

The documentation page will be scrolled, but not the contents in the `AppSettingsDialog`. If tested in Chromium the contents in the `AppSettingsDialog` will be scrolled and, once it is not possible to scroll further, then the documentation page will be scrolled.

*It also happens when the AppSettingsDialog component is used in apps, but the documentation is the easiest place to check :-)

**Comment by susnux** [comment]
I can not reproduce this using Firefox 113 on Linux. Scrolling using mouse and using keyboard (arrow keys) both work:


https://github.com/nextcloud/nextcloud-vue/assets/1855448/9b2bd5ee-ef8b-4785-9cbf-818be363853a

**Comment by susnux** [comment]
Probably fixed with dialog migration
