### ISSUE TITLE
Actions menu / Popover flying arrow on close

### ISSUE THREAD

**Issue by PVince81** [nextcloud-libraries/nextcloud-vue#1610]
To be able to see it, need the actions popover to overlay some dark background.

### Steps

1. Open the talk app
1. Start a call (no other participants needed)
1. Click the three dots on the top right and focus your eyes on the arrow
1. Click outside to close the actions popover
1. Repeat the last two steps and look for the arrow

### Expected result
The closing animation of the menu doesn't leave a flying arrow.

### Actual result
The arrow will move to some direction and keep its opacity until the menu is closed.

With the arrow, I mean this one:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/277525/100331625-b0bfe080-2fd0-11eb-96dd-99b4731e4aec.png">

![popover-arrow-animation](https://user-images.githubusercontent.com/277525/100332217-69861f80-2fd1-11eb-907e-6ad7d774e0ca.gif)

**Comment by PVince81** [comment]
It as only solved by https://github.com/nextcloud/nextcloud-vue/pull/831 by pure luck.

I found the root cause: during the closing animation of the Actions menu, the property "opened" is already set to false, and the menu contents DOM is cleared too early. This is what prompts popper to update the position during the animation.

A quick fix is to remove the "opened" condition and always let the menu render itself, even when not opened.
Another idea would be to add an extra flag to disable rendering that toggles after a delay. But not sure if such flag is worth the hassle...

**Comment by PVince81** [comment]
quick patch here:

```diff
diff --git a/src/components/Actions/Actions.vue b/src/components/Actions/Actions.vue
index a586b75..f88e23b 100644
--- a/src/components/Actions/Actions.vue
+++ b/src/components/Actions/Actions.vue
@@ -140,7 +140,7 @@ https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-action
                        </button>
 
                        <!-- Menu content -->
-                       <div v-show="opened"
+                       <div
                                ref="menu"
                                :class="{ open: opened }"
                                tabindex="-1"
@@ -154,7 +154,7 @@ https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-action
                                @mousemove="onMouseFocusAction">
                                <!-- menu content -->
                                <ul :id="randomId" tabindex="-1">
-                                       <template v-if="opened">
+                                       <template>
                                                <slot />
                                        </template>
                                </ul>
```

but I now still have mixed feelings... if Actions menus are used in a list, it might cause too many DOM elements to be rendered.

In general I'd rather expect the VPopover/v-tooltip/popper to destroy its contents after hiding.

**Comment by PVince81** [comment]
to clarify, Popper (the v-tooltip and Popover backend) has a resize observer that checks if the popup contents changes

whenever we flip the "opened" state, it will render or unrender the elements inside the popup, which is detected as change, so popper will update the popup's position

now, since we also have some animation in place, it will animate to the new position

**Comment by raimund-schluessler** [comment]
@PVince81 Is this still an issue?

**Comment by PVince81** [comment]
yes, reproducible on c.nc.com (NC 24.0.4rc1)

<img width="184" alt="image" src="https://user-images.githubusercontent.com/277525/186460521-6c9ceffb-7991-4797-b9ec-47310690b1e7.png">

this time it's on this menu, if you open and close multiple times, you can see the arrow flying to the right

once Talk is updated to floating-vue (are we using it for popovers now?) we can try again

**Comment by PVince81** [comment]
I tried again, I needed to click 10-15 times with different speeds to make it appear.

Now, am not sure if it's worth fixing... The only thing that matters I think is that we move away from v-tooltip for the Popover, as v-tooltip has many issues with timings and events.

**Comment by raimund-schluessler** [comment]
We use `floating-vue` now for the popovers. @PVince81 Could you check whether this still is an issue for you, please?

**Comment by susnux** [comment]
Should be fixed with using `floating-vue`, if you still experience the issue please reopen.
