### ISSUE TITLE
Let us enter custom hex values in color pickers

### ISSUE THREAD

**Issue by junpet** [nextcloud-libraries/nextcloud-vue#1687]
Currently we can select from some predefined colors and open the color picker and pick one color, but it would be nice if we could use exact hex values.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I can only select colors from the palette, which won't be the same as the desired hex value.

**Describe the solution you'd like**
I would like to use specific hex values for colors.

**Describe alternatives you've considered**
~~I found out you can use your browser's Inspect (element) feature. Search for the following element: `div.vc-chrome-active-color` and replace the RGB values in the `style` property `rgb(182, 70, 157)`.~~ The entered value won't be send with the Choose button.

**Additional context**
![image](https://user-images.githubusercontent.com/3465278/96964174-4cf65380-150a-11eb-84d8-fe5cb588fc10.png)

**Comment by EngelPika32** [comment]
IMHO this issue is way overdue. I don't see any reason why this isn't implemented yet (I'd like to understand the reasons, please tell me).

> Alternatively, using the native color picker via `<input type="color" ...>` is a better way, as realized by the calendar app.
I remember seeing this picker in nextcloud as well, though looking at the calendar app now it's gone??

Either implement a color input yourself or use the default color input (it exists for a reason, I suppose. Why still not… use it?)

PS: I'm coming from nextcloud/deck/issues/1911

**Comment by Jaxom99** [comment]
From what I see, it's possible now ton enter the hex code (on second click). I'm on version 26.0.4.
Maybe time to close the issue ?

_And if you're looking into color issues, please give love to this one, about the default palette => #2214_

**Comment by Gchbg** [comment]
I would also be very interested in this. My use case is setting brand colors for Kanban boards in Deck.

**Comment by ShGKme** [comment]
`NcColorPicker` component supports custom values. If it is not available in a specific app - it is not enabled in a specific place in the app.
