### ISSUE TITLE
Create general purpose editable text field component

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud-libraries/nextcloud-vue#1749]
As discussed in the frontenders channel, we're upstreaming this from talk

- [ ] Come up with a better design for the counter;
- [ ] Find appropriate name;

https://user-images.githubusercontent.com/26852655/110457792-eb9edd80-80c2-11eb-8bf1-ca571e1e2351.mp4

**Comment by violoncelloCH** [comment]
Whats the difference between this an `RichContenteditable`? Or is this actually an addition on top of `RichContenteditable`?

**Comment by ma12-co** [comment]
It's a wrapper of it that adds the buttons, feedbacks and the different styles basically.
