### ISSUE TITLE
Deduplicate Bundles

### ISSUE THREAD

**Issue by jotoeri** [nextcloud-libraries/nextcloud-vue#1779]
Especially, when importing multiple components, the packages of l10n and iconfonts are duplicated within each component.
Several Ansatzes to check (taken from #1775):
- [ ] Move to webpack 5, probably this gives better tree-shaking
- [ ] Use chunks for l10n.js & iconfonts, so webpack can separately import them on apps?
- [ ] Import these chunks somehow conditionally, if possible. E.g. if an app does not use the info-icon of SettingsSection, iconfonts dont have to be imported at all for this.

**Comment by juliushaertl** [comment]
See https://github.com/nextcloud/nextcloud-vue/issues/251#issuecomment-465506227 for additional context on why webpack was probably a bit of a bad choice there at least at the moment.

**Comment by susnux** [comment]
We are using vite now which supports proper tree shaking #4329
