### ISSUE TITLE
Allow custom actions inside Actions component

### ISSUE THREAD

**Issue by dartcafe** [nextcloud-libraries/nextcloud-vue#1962]
As a developer, I want to use custom actions inside the action slot to deduplicate code. 

I.e. in polls we created a custom action for deletion of several items: https://github.com/nextcloud/polls/blob/master/src/js/components/Actions/ActionDelete.vue

Currently actions component must be registered and applied inside the custom component, wich prevents using it inside an actions menu.

**Comment by raimund-schluessler** [comment]
@dartcafe Can you check if this issue is still valid, please? I think it should work now.

**Comment by dartcafe** [comment]
As soon, as I have time. Sorry, busy atm.

**Comment by Antreesy** [comment]
Allowed with limitations

**Comment by dartcafe** [comment]
Just checked with v9. Custom and reusable actions are still not possible.
