### ISSUE TITLE
Text string in "Comments" text box

### ISSUE THREAD

**Issue by Valdnet** [nextcloud-libraries/nextcloud-vue#2027]
Steps:

1. Select file details.
2. Go to the "Comments" tab.

The text string in the "Comments" text box is too long. In English, it ends with an arrow, while in other translations it can go beyond the text field.

![obraz](https://user-images.githubusercontent.com/47037905/121510094-94711780-c9e7-11eb-8fd0-2d46e044adaa.png)

![obraz](https://user-images.githubusercontent.com/47037905/121510258-ba96b780-c9e7-11eb-9101-c6c7d6d5f1a5.png)

App:
Nextcloud 22.0.0 beta 2 and 21.0.2
Comments 1.11.0

Browser:
Firefox 89.0

**Comment by solracsf** [comment]
Fixed by https://github.com/nextcloud/server/pull/40294 (v28 only)

**Comment by ShGKme** [comment]
Fixed by #4408
