### ISSUE TITLE
Increase font-size in input fields to standard (15px)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud-libraries/nextcloud-vue#2172]
Currently the font-size in input fields is 13px, whereas the body text is 15px. We should bump up the input field font-size to match that.

Otherwise it looks very odd, especially as seen here in the profile info:
![image](https://user-images.githubusercontent.com/925062/129893193-b70018fe-73db-45d3-8bf9-de38df3277ad.png)

cc @marcoambrosini @nimisha-vijay as discussed.

**Comment by jancborchardt** [comment]
Seems that we need to put this in some planning bucket since it otherwise doesn’t get done. Is it for server, or Talk since @marcoambrosini wanted to work on it? cc @AndyScherzinger @PVince81 @nickvergessen

**Comment by AndyScherzinger** [comment]
Since @marcoambrosini wants to work on it and if @nickvergessen agrees that it fits the Talk 14 schedule (as-in not cannibalizing the planned features there) I'd say put it in the Talk board. Else we need to discuss which team has the capacity to pick it up.

**Comment by jancborchardt** [comment]
@marcoambrosini @nickvergessen since in Talk it was moved back to "Planning evaluation", possibly we need to move it to a different team? @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Depends on when Marco might be able to pick it up. Same applies for any other team, currently everyone is working on polishing of v26 for 26.0.1 - @nickvergessen could Maksim cover it maybe?

**Comment by marcoambrosini** [comment]
I'd say this is solved with the new input components.
https://github.com/nextcloud-libraries/nextcloud-vue/pull/2868#issue-1313167575

I would close this and open the issue in the few places where we find that there are rules overriding the styles if everyone agrees

**Comment by jancborchardt** [comment]
@marcoambrosini yeah, or rather than issues it could be directly pull requests to fix it? :)

**Comment by marcoambrosini** [comment]
Fixed!
