### ISSUE TITLE
Colorpicker: add ability to specify color palette.

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud-libraries/nextcloud-vue#2214]
Add ability to specify the default color palette for developers.

**Comment by Antreesy** [comment]
Closed with:
- https://github.com/nextcloud-libraries/nextcloud-vue/commit/ee6fbe3b945ecb0738c18bee077e2e42f196d66a
- https://github.com/nextcloud-libraries/nextcloud-vue/commit/8d1b3ff21cf27cf044fe0a6b33a846710d5d9626
