### ISSUE TITLE
ActionLink does not display icon when a URL is passed

### ISSUE THREAD

**Issue by Pytal** [nextcloud-libraries/nextcloud-vue#2315]
When a URL is passed into the `icon` prop on `ActionLink` no icon is displayed. This should work correctly like when passing a CSS class.

This only occurs with a single action, and otherwise works correctly when there are multiple actions or a dropdown menu is forced `:force-menu="true"`

**Comment by juliushaertl** [comment]
Could be that this is already fixed with https://github.com/nextcloud/nextcloud-vue/pull/2532 can you check that maybe?

**Comment by Pytal** [comment]
Will test this when 5.1.1 is released

**Comment by Pytal** [comment]
@juliushaertl I can confirm that the icon is still blank when passing a URL as the `icon` prop

**Comment by raimund-schluessler** [comment]
We discourage using icon-classes now. How do we go about URL being passed? @skjnldsv?
