### ISSUE TITLE
Allow lazy loading of emoji picker

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud-libraries/nextcloud-vue#2539]
When profiling the text app we noticed that the menubar and in particular the emoji picker took a long time to render.
Loading the menubar after the initial text was rendered saved ~800 ms on the text render.

However it's not ideal to postpone rendering the entire menu bar. I suspect that loading the picker is what makes the emoji picker component take a long time to load. So if we could lazy load the picker that might allow us to render the menubar together with the text without waiting for the picker to complete rendering.

I imagine something like this:
```vue
<EmojiPicker 
  ...
  :loadPicker="mainContentLoaded" >
  <button>
</EmojiPicker>

```
When `mainContentLoaded` becomes true the picker would be loaded.

**Comment by max-nextcloud** [comment]
I tried to figure out if this was text specific and disabled the EmojiPicker in talk. In my dev instance an empty talk room will render approx. 1 sec. faster without the emoji picker:
Of course it would be ideal to just have the picker load fast - but for now i think lazy loading seems more doable.

**Comment by Antreesy** [comment]
Solved with https://github.com/nextcloud-libraries/nextcloud-vue/pull/4479 (delayed first init, shared data afterwards)
