### ISSUE TITLE
Change default colors in the color Picker

### ISSUE THREAD

**Issue by burnhard93** [nextcloud-libraries/nextcloud-vue#2648]
Hey :)

it would be really cool if it would be possible to change the default colors in the color picker.
The default ones are not very handsome :D

Something like that would be amazing:
![grafik](https://user-images.githubusercontent.com/35692724/106170764-18d9a100-6191-11eb-9c73-7d0e89c0270e.png)

Thanks anyway :)

**Comment by tcitworld** [comment]
Off-topic now : A limitation we also have in the calendar case is that the colors need to match to CSS3 color names as defined [in the spec](https://datatracker.ietf.org/doc/html/rfc7986#section-5.9) (an errata allows to use rgb() instead, but we don't know how much this is considered).

**Comment by Antreesy** [comment]
Closed with:
- https://github.com/nextcloud-libraries/nextcloud-vue/commit/ee6fbe3b945ecb0738c18bee077e2e42f196d66a
- https://github.com/nextcloud-libraries/nextcloud-vue/commit/8d1b3ff21cf27cf044fe0a6b33a846710d5d9626
