### ISSUE TITLE
Border radius large for all inputs 

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud-libraries/nextcloud-vue#2751]
Is it time yet? @jancborchardt @nimishavijay 

current:
<img width="423" alt="Screenshot 2022-06-10 at 09 35 23" src="https://user-images.githubusercontent.com/26852655/173015038-06e7e583-81f7-45bd-8120-b01e202ba111.png">
 
proposed: 
<img width="423" alt="Screenshot 2022-06-10 at 09 37 39" src="https://user-images.githubusercontent.com/26852655/173015198-905470af-f166-4be5-a5c8-55afa8a6e8f6.png">

**Comment by marcoambrosini** [comment]
Or large at least? 

<img width="321" alt="Screenshot 2022-06-10 at 09 41 21" src="https://user-images.githubusercontent.com/26852655/173018458-af5508d8-5bd9-41d2-8c4e-4b87724d4223.png">

**Comment by jancborchardt** [comment]
Yup - for sure is that we can move to radius large for the inputs. :)

Just make sure to adjust it in the legacy non-Vue CSS too so it is applied on log in, install and other pages.

**Comment by raimund-schluessler** [comment]
> We could also think about using that for the buttons so we unify – cause it seems a bit strange to use large radius for inputs and pill for buttons? @marcoambrosini @nimishavijay

Would look like this for buttons:
![Screenshot 2022-06-15 at 17-28-49 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/173866451-9cd63faa-3a23-43e0-ad41-d3ec6165fec9.png)

And breadcrumbs would need an adjustment as well, with this result:
![Screenshot 2022-06-15 at 17-31-19 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/173866881-06b9f780-4638-4ad3-9054-1d436c4e665d.png)

**Comment by marcoambrosini** [comment]
me not like it 🙊

**Comment by Antreesy** [comment]
Resolved with NC30 design
