### ISSUE TITLE
Add a square button property

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud-libraries/nextcloud-vue#2873]
Something like we do for buttons in the header:
![https://user-images.githubusercontent.com/213943/180236022-6964ec5d-77e6-48b3-a3d3-ae03bb890ffe.png](https://user-images.githubusercontent.com/213943/180236022-6964ec5d-77e6-48b3-a3d3-ae03bb890ffe.png)

Should be possible for primary and secondary buttons too?

**Comment by Antreesy** [comment]
Obsolete with NC30 design
