### ISSUE TITLE
Border shape of active state in "tertiary-on-primary" button does not match focused state

### ISSUE THREAD

**Issue by danxuliu** [nextcloud-libraries/nextcloud-vue#2893]
The _:active_ state of the `tertiary-on-primary` button introduced in https://github.com/nextcloud/nextcloud-vue/pull/2871 shows a round background for the button, even if the box shadow is (almost) square when focused:
![Tertiary-On-Primary-Active](https://user-images.githubusercontent.com/26858233/180664086-000c73e8-731f-470a-9353-71eefb5eed2a.png)
![Tertiary-On-Primary-Focused-Light-After](https://user-images.githubusercontent.com/26858233/180663913-cd7fff04-fbec-43c8-b24e-fb30ebeac575.png)

The _:active_ state can be triggered by pressing on the button and then moving the cursor away so it no longer hovers it ([as _:hover_ overrides _:active_](https://developer.mozilla.org/en-US/docs/Web/CSS/:active)).

By default [buttons in the _:active_ state change their background colour](https://github.com/nextcloud/nextcloud-vue/blob/498364d197c5257d758a48853abf87f71ba1d8d2/src/components/Button/Button.vue#L501-L503), except [primary](https://github.com/nextcloud/nextcloud-vue/blob/498364d197c5257d758a48853abf87f71ba1d8d2/src/components/Button/Button.vue#L592-L596), [success](https://github.com/nextcloud/nextcloud-vue/blob/498364d197c5257d758a48853abf87f71ba1d8d2/src/components/Button/Button.vue#L651-L655), [warning](https://github.com/nextcloud/nextcloud-vue/blob/498364d197c5257d758a48853abf87f71ba1d8d2/src/components/Button/Button.vue#L665-L669) or [error](https://github.com/nextcloud/nextcloud-vue/blob/498364d197c5257d758a48853abf87f71ba1d8d2/src/components/Button/Button.vue#L679-L683) buttons, in which the _:active_ state is not distinguishable from the inactive state; that might need to be fixed too (although that seems to be done on purpose, so maybe it is fine that way, I do not know).

**Comment by Antreesy** [comment]
Resolved with NC30 design
