### ISSUE TITLE
TextField produces invalid HTML

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud-libraries/nextcloud-vue#2972]
There is a invalid `trailingbuttonicon="close"` HTML attribute on the resulting input element.
The issue is that we forward all props in the v-bind of TextField:
https://github.com/nextcloud/nextcloud-vue/blob/de6362d03bf368f486ecdb753344ca137582fbe1/src/components/TextField/TextField.vue#L115

As well as InputField:
https://github.com/nextcloud/nextcloud-vue/blob/de6362d03bf368f486ecdb753344ca137582fbe1/src/components/InputField/InputField.vue#L31

From my POV the TextField should strip out the prop and not forward it, as it handles it by itself.

**Comment by marcoambrosini** [comment]
Ok we'll just need to pass down the props one by one then

**Comment by skjnldsv** [comment]
Relevant: https://github.com/nextcloud/nextcloud-vue/issues/3479

**Comment by susnux** [comment]
Fixed by @ShGKme in https://github.com/nextcloud-libraries/nextcloud-vue/commit/0cf240bb83a16620b92a1e3db24e8237ea41485b
