### ISSUE TITLE
Datetime picker has unnecessary box-shadow

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud-libraries/nextcloud-vue#3195]
Datetime picker has a `box-shadow: inset 0 1px 1px rgba(0,0,0,0.075)`, which makes it look inconsistent from the other input fields. If the shadow is removed it would look a lot cleaner. 

Example screenshots from availability setting and the calendar event sidebar.
![image](https://user-images.githubusercontent.com/52440189/189116440-01219512-0a21-4078-a1e8-b6f3591f23f9.png)
![image](https://user-images.githubusercontent.com/52440189/189116604-bac17c9c-677e-4350-925f-e067dfba3c0a.png)

Tested on the tech-preview instance on Firefox

**Comment by aryatalathi** [comment]
Can I work on this? Thank you.

**Comment by Antreesy** [comment]
Resolved in current state
