### ISSUE TITLE
[NcInputField] Support inputmode

### ISSUE THREAD

**Issue by dartcafe** [nextcloud-libraries/nextcloud-vue#3246]
For mobile devices `inputmode` is very helpful to select the right keyboard.

Suggestion: 

```html
	<input :inputmode="inputmode" />
```

```js
	props: {
		inputmode: {
			type: String,
			default: null,
			validator(value) {
				return ['text', 'none', 'numeric', 'email', 'url'].includes(value)
			},
		},
	},

```

Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

**Comment by susnux** [comment]
Attributes are forwarded to the input element:
https://github.com/nextcloud-libraries/nextcloud-vue/pull/3485
