### ISSUE TITLE
Multiselect height changes on focus/blur

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud-libraries/nextcloud-vue#3363]
Example: 

![Peek 2022-10-14 09-21](https://user-images.githubusercontent.com/6078378/195797897-176171e9-f280-4e3e-90d9-f0dbedd99dca.gif)

**Comment by ChristophWurst** [comment]
The image is cut off at the bottom. But if you look closely you can see that the next element moves up/down with the focus/blur
