### ISSUE TITLE
Multiselect pixel and tabbing issues

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud-libraries/nextcloud-vue#3377]
* [ ] When tabbing to a value but not confirming via enter, then coming back to it, wrong value is preselected 
![Peek 2022-10-18 17-23](https://user-images.githubusercontent.com/213943/196473862-0f75bf2e-f314-44f6-a8f5-2288ab53418c.gif)

* [ ] Text input vs actual value shifts by 1 px
![Peek 2022-10-18 17-27](https://user-images.githubusercontent.com/213943/196474767-0b1eac3a-4a1a-42f4-88ea-0c556e224a89.gif)

* [ ] Rounded corners for dropdown (see above)

Was remarked in the Design review of files_retention: https://github.com/nextcloud/files_retention/issues/222

**Comment by susnux** [comment]
Multiselect was replaced by NcSelect
