### ISSUE TITLE
Feature request: native title tooltip on NcListItem title

### ISSUE THREAD

**Issue by ShGKme** [nextcloud-libraries/nextcloud-vue#3687]
It seems to be impossible to set the `title` attribute on `<NcListItem>`.

What about adding a `nativeTitle` prop or even more, adding title-tooltip feature for long titles to `NcListItem`?

Use case: display full title (from prop) in title (tooltip), when it is too long.

![Tooltip on a long conversation name with ellipses](https://user-images.githubusercontent.com/93392545/214914351-9ca30e36-6c0d-4476-90b6-b0610adaa260.png)

Related:
- https://github.com/nextcloud/nextcloud-vue/issues/2503
- https://github.com/nextcloud/spreed/pull/8605

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/NcListItem/NcListItem.vue#L140

Documentation says it's there.
I think they are automatically passed on when they are not props. So simply using title works already.

**Comment by ShGKme** [comment]
> https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/NcListItem/NcListItem.vue#L140
> 
> Documentation says it's there. I think they are automatically passed on when they are not props. So simply using title works already.

But `title` is a prop:

https://github.com/nextcloud/nextcloud-vue/blob/e65bd9247874264aa1d57d59d79f53391e31faa1/src/components/NcListItem/NcListItem.vue#L321-L327

It is used only as the text content of the title element:

https://github.com/nextcloud/nextcloud-vue/blob/e65bd9247874264aa1d57d59d79f53391e31faa1/src/components/NcListItem/NcListItem.vue#L230-L234

**Comment by Antreesy** [comment]
Seems closed by https://github.com/nextcloud-libraries/nextcloud-vue/pull/4106
