### ISSUE TITLE
`NcSelect` lower right corner not rounded

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud-libraries/nextcloud-vue#3799]
@pytal For long, scrolling lists in the `NcSelect` component, the lower right corner is not rounded:
<img width="282" alt="NcSelect" src="https://user-images.githubusercontent.com/2496460/220140729-128bdb37-7b17-4505-93e3-3ceb2b28b0a2.png">

Happens in Firefox, Chrome is alright.

**Comment by Pytal** [comment]
Seems to be due to the scrollbar radius 🤔

The scrollbar pseudo-elements https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar are not supported by Firefox but will look into solutions

**Comment by raimund-schluessler** [comment]
Cannot reproduce this anymore. Seems to work now.
