### ISSUE TITLE
`NcRichContenteditable` pasting HTML alike content strips off text

### ISSUE THREAD

**Issue by susnux** [nextcloud-libraries/nextcloud-vue#3908]
Maybe related to #3264 but even worse:

Pasting HTML alike content strips content instead of replacing it with the HTML entities,
For example pasting
````markdown
```java
Test<Object> myMethod() {
}
```
````

Will result in:
````markdown
```java
Test myMethod() {
}
```
````

![image](https://user-images.githubusercontent.com/1855448/226343960-8716c6af-fb21-4d4d-a693-c94b82fb74f2.png)

**Comment by Antreesy** [comment]
Paste was solved with #3915, but rendering is broken:
 - at second NcRichContenteditable (not a big deal, unlikely there will be two components linked to the single data source)
 - inside multiline code block at NcRichText with markdown

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/755f80ed-eee9-463b-b127-f93dc6f6a13e)
