### ISSUE TITLE
node version incompatible with dependency @skjnldsv/sanitize-svg@1.0.2

### ISSUE THREAD

**Issue by DennisCodeBuds** [nextcloud-libraries/nextcloud-vue#3950]
Hello, 

When trying to ` yarn add @nextcloud/vue` running in a `node:14-alpine` container I get the following error : 

```
error @nextcloud/typings@1.6.0: The engine "node" is incompatible with this module. Expected version "^16.0.0". Got "14.21.3"
error Found incompatible module.
```

However when running in a  `node:16-alpine` container I get the following :
```
error @skjnldsv/sanitize-svg@1.0.2: The engine "node" is incompatible with this module. Expected version "^14.0.0". Got "16.20.0"
error Found incompatible module.
``` 

The requirements for @nextcloud/vue : node:^16.0.0 and
@skjnldsv/sanitize-svg@1.0.2 : node:^14.0.0 
are incompatible. 

Any way to get this running without having to fork one of those two packages and change the node version requirement ?

**Comment by raimund-schluessler** [comment]
It's just a warning. You can ignore it for now, the compilation works fine. We will switch away from skjnldsv/sanitize-svg anyway.

**Comment by DennisCodeBuds** [comment]
Strange when running this with yarn it is an error but with npm it works ...

**Comment by susnux** [comment]
Dependency was dropped https://github.com/nextcloud-libraries/nextcloud-vue/pull/4557
