### ISSUE TITLE
Sidebar tabs design update

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud-libraries/nextcloud-vue#4034]
- [x] Remove border
- [x] Ellipse text instead of 2 lines

As discussed with @jancborchardt

**Comment by dartcafe** [comment]
Does it address this "feature"? 
![grafik](https://user-images.githubusercontent.com/26707476/236701322-90e11676-3f70-473f-ba9b-03eaf21edfd0.png)

**Comment by marcoambrosini** [comment]
So I've been a bit reluctant with this because I think our current system doesn't work and we need to think this through a bit more. I think that we need to take a step back here and rethink how we do the sidebar altogether. I'm closing for now as this is just a cosmetic change that is not solving problems and in fact ellipsizing text on buttons is something that we've come to normalise but is just unacceptable.

<img width="363" alt="Screenshot 2023-08-22 at 09 44 05" src="https://github.com/nextcloud-libraries/nextcloud-vue/assets/26852655/974b25cd-5dfb-4917-90c5-b6ff4d44f296">

**Comment by marcoambrosini** [comment]
I thought I was the only one that disliked the border so I figured I should leave it there as it doesn't really solve much. Implemented now. 
Label trimming is already in.

**Comment by ShGKme** [comment]
@marcoambrosini what do you think about some multiline tabs design when text is not truncated? Taking into account that we have many apps with many tabs, many apps that adds more tabs (to files for example) and etc. Like very classic tabs, but with this pillow design

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/6b81d6aa-9ea2-4254-9570-8a7e4adf30eb)

**Comment by marcoambrosini** [comment]
@ShGKme That's one of the approaches I was thinking about, but visually they would look more like chips. I don't think it's the best approach though. I think the most viable solution is to remove the labels and have 44x44px buttons.
