### ISSUE TITLE
Autocomplete adds spaces before mention-parameter

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud-libraries/nextcloud-vue#4127]
![image](https://github.com/nextcloud/nextcloud-vue/assets/1580193/7ab2b97e-1961-4700-9dd7-7516d85de9b2)

Video:

https://github.com/nextcloud/nextcloud-vue/assets/1580193/85842158-928e-43f1-92bb-5a40858346d2

This is reproducible when sending messages in Talk and mentioning someone. You only had 1 space before the "@" when writing the message, but have 3 spaces after sending it.

**Comment by Antreesy** [comment]
https://github.com/nextcloud-libraries/nextcloud-vue/blob/cb58beb70b21fefd5b342a154edeb62f12d86884/src/mixins/richEditor/index.js#L148-L150

As HTML replaces new lines, empty lines and consecutive whitespaces with a single whitespace, which parseContent() can't trim, we might look for a solution to make it manually. So far works:

```js
const renderedHtml = wrapper.innerHTML.replace(/>\s+</g, '><')
```

See discussion at https://github.com/nextcloud-libraries/nextcloud-vue/pull/5359#discussion_r1516411454
