### ISSUE TITLE
Fix vertical alignment of text in nccounterbubble

### ISSUE THREAD

**Issue by szaimen** [nextcloud-libraries/nextcloud-vue#4200]
As discussed with @jancborchardt and @nimishavijay, the text inside the counterbubble should be positioned right in the center and not a bit off.

See the following screenshot:
![image](https://raw.githubusercontent.com/nextcloud/documentation/02a3c92edab2984ef47758d0df8076fe3d4492c5/developer_manual/images/talk-counter-bubble.png)

**Comment by szaimen** [comment]
As @nimishavijay and me found out this happens due to the font-family used. In our case it got fixed by using `sans-serif`. Maybe we should enforce this here?

**Comment by jancborchardt** [comment]
The font should be the same as used elsewhere, otherwise that will look off instead.

How is the centering currently achieved? We can change the approach, either via vertical align, or padding, or however possible.

**Comment by szaimen** [comment]
> The font should be the same as used elsewhere, otherwise that will look off instead.

It uses the first font that is installed on the system in this order: `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Cantarell, Ubuntu, "Helvetica Neue", Arial, sans-serif, "Noto Color Emoji", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol`

> How is the centering currently achieved? We can change the approach, either via vertical align, or padding, or however possible.

The problem is indeed the font and not the centering itself. On macOS for example everything looks fine since a different system font, probably -apple-system or BlinkMacSystemFont is used.

See the following screenshot that shows this pretty clearly on my system:
![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/0ac6da14-376e-48f8-8c89-f9f972f98a37)

**Comment by szaimen** [comment]
So it seems to come down to system font rendering here...

**Comment by szaimen** [comment]
Should we enforce a specific font then here?

**Comment by szaimen** [comment]
also cc @marcoambrosini

**Comment by nimishavijay** [comment]
There were issues with using custom fonts in the past, if I remember correctly? My worry is that changing something like the font for this one element will both look out of place visually and not render correctly if that font is not supported/installed on the system.

**Comment by marcoambrosini** [comment]
Who did the original screenshot? Could we gather more information about where it looks bad and try to find out why?

**Comment by szaimen** [comment]
@marcoambrosini this is on my windoes 11 machine. It happens due to the system font used. Please read the conversation above.

**Comment by marcoambrosini** [comment]
Yeah I've seen that but I was missing the OS info. Does that happen on all browsers?

**Comment by szaimen** [comment]
@nextcloud/designers what do we do here then?

**Comment by nimishavijay** [comment]
I would vote against changing the font. If there is a way to change the padding on only the problematic browsers/OSes/etc that would fix it, is that technically feasible?

**Comment by susnux** [comment]
Maybe we can reorder the fonts? This might help for windows without any logic changes.

**Comment by szaimen** [comment]
> Maybe we can reorder the fonts? This might help for windows without any logic changes.

This might be a good idea indeed. I just tested and "Segoe UI" seems to be the culprit. Even with Roboto (which comes directly after it it works)...

**Comment by szaimen** [comment]
I opened https://github.com/nextcloud/nextcloud-vue/pull/4271 for a test. With that everything looks good on my end:
![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/6d5bf5c9-0a52-4e24-83cc-b990e7112cef)
The correct PR is in https://github.com/nextcloud/server/pull/39008/files

**Comment by susnux** [comment]
see https://github.com/nextcloud/server/pull/39008

**Comment by szaimen** [comment]
I fear this doesnt fix the problem unfortunately.

**Comment by jancborchardt** [comment]
Any update regarding this? At least in Talk at 100% it looks fine, and on the Vue components page as well? https://nextcloud-vue-components.netlify.app/#/Components/NcCounterBubble
(Although the outlined example shows as white on white for me.)

**Comment by szaimen** [comment]
> Any update regarding this? At least in Talk at 100% it looks fine, and on the Vue components page as well? https://nextcloud-vue-components.netlify.app/#/Components/NcCounterBubble (Although the outlined example shows as white on white for me.)

It depends on the system font used. It is broken on windows with segoe ui afaik

**Comment by jancborchardt** [comment]
@szaimen as far as you know or it is the case? :) Could you test on Windows to confirm/reproduce again with master or so we can close the issue?

**Comment by ShGKme** [comment]
On Windows with Segoe UI (default)
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/cbefafba-44e7-444e-9ae0-be875bc61342)

**Comment by szaimen** [comment]
Indeed, we cannot fix this because Segoe UI is broken. Since we also decided to not use a different font, I will close this.
