### ISSUE TITLE
[BITV] Special buttons color contrast improvements

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud-libraries/nextcloud-vue#4324]
As discussed in #4193 the color contrast of the special buttons (success, warning, error buttons) is not sufficient. 

So the new color codes we could use are:
`--color-error`: `#E71F18`
`--color-success`: `#328544`

![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/155da565-df47-4623-8c8f-b00b9e4ae803)

This would also affect other components using these colors such as NcNoteCard. 
@nextcloud/designers agree that all occurrences of the warning button can be replaced by either error or secondary button. Hence the warning color can remain unchanged. 

cc @JuliaKirschenheuter @marcoambrosini @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Looks good to me, great choice of tone, easier on the eyes (on bright displays I think) 👍

**Comment by szaimen** [comment]
Looks good 👍
