### ISSUE TITLE
Pressing Esc key on Link picker dialog closes the document

### ISSUE THREAD

**Issue by pedropintosilva** [nextcloud-libraries/nextcloud-vue#4328]
Pressing Esc key on Link picker dialog closes the document instead of closing the dialog.

**To Reproduce**
1. Go to 'Insert tab'
2. Click on 'Smart Picker'
3. Now press Shift + Tab to got from the input to the previous element (close button)
4. Press Escape key
5. The document gets closed; we are now back to files view with that dialog still opened

**Expected behavior**
Escape should just close the dialog

-----

- server on #706c141fffce928d344fe2f039da549fad065393 
- richdocuments on fix/target-picker
- viewer on #09996635005556bfc984de06d24568163b764a5d

**Comment by juliushaertl** [comment]
Seems that the modal listener might be too global and not preventing the escape event to propagate if two modals are open:

https://github.com/nextcloud/nextcloud-vue/blob/0e61454cf5f0c313409da4bc4645fb7fa8aaef2a/src/components/NcModal/NcModal.vue#L600-L615

In addition @julien-nc Do you remember why canClose was set to false in https://github.com/nextcloud/nextcloud-vue/blame/0e61454cf5f0c313409da4bc4645fb7fa8aaef2a/src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue#L4?

**Comment by juliushaertl** [comment]
Could not reproduce on tech-preview but on local master, so maybe something changed between 27 and master

**Comment by juliushaertl** [comment]
No longer reproducable, just pressing esc on the close button does not work:

Likely the modal is not handling escape but the picker component:
https://github.com/nextcloud-libraries/nextcloud-vue/blob/master/src/components/NcRichText/NcReferencePicker/NcReferencePickerModal.vue#L9
https://github.com/nextcloud-libraries/nextcloud-vue/blob/master/src/components/NcRichText/NcReferencePicker/NcReferencePicker.vue#L10
