### ISSUE TITLE
[BITV] Change heading in EmptyContent to span

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud-libraries/nextcloud-vue#4338]
This is an accessibility issue.

There is `<h2>` heading inside of `name` slot https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/NcEmptyContent/NcEmptyContent.vue#L148-L152. This creates problems across heading issues, because `<h2>` heading fits only in some rare cases.

Example: 

In search dropdown menu `<h2>` doesn't fits and creates other semantic problems on the page. `<h2>` is used for much more significant palaces on the page.
![Screenshot from 2023-07-17 10-51-37](https://github.com/nextcloud/nextcloud-vue/assets/6078378/005d1ce0-a9e5-4d1b-878e-16ce351d0bc6)

We should separate styling and semantics. I would suggest to use styles from `<h2>` but create `<p>` instead for the `name` slot.

@nimishavijay @marcoambrosini what do you think?

**Comment by susnux** [comment]
I think this would be the correct solution as for all other cases you can already just use the header slot.
(e.g. like collectives uses it)

**Comment by JuliaKirschenheuter** [comment]
> I think this would be the correct solution as for all other cases you can already just use the header slot. (e.g. like collectives uses it)

But then how could i make sure that inside of the `<slot>` is no heading?
