### ISSUE TITLE
adjust border color of components to match each other

### ISSUE THREAD

**Issue by szaimen** [nextcloud-libraries/nextcloud-vue#4345]
See 
![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/70695157-6d1d-4dae-89a2-e8d214ec9c08)

It is about this component https://nextcloud-vue-components.netlify.app/#/Components/NcCheckboxRadioSwitch to match this one https://nextcloud-vue-components.netlify.app/#/Components/NcSelect?id=ncselect-1

Suggested:
| Before | After |
|---|---|
| ![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/f3cf0499-71cc-4309-b9d8-f09d4623ff65) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/42591237/9bdbb0ac-3ae5-4a67-a7e9-188f9ff40b73) |

cc @nextcloud/designers

**Comment by susnux** [comment]
The mention does not work here @szaimen because that team is not part of this organization.

**Comment by szaimen** [comment]
cc @jancborchardt @marcoambrosini

**Comment by jancborchardt** [comment]
Yep seems fine by me!
