### ISSUE TITLE
Translations are not working for some languages, even though the translation strings are present in the translation pot file.

### ISSUE THREAD

**Issue by vishnu-n23** [nextcloud-libraries/nextcloud-vue#4384]
Slovakian translations are not working inside Nextcloud Vue components; it always displays the fallback (English strings). I tried changing the locale too, but it didn’t work.
![nextcloud vue components translation issue](https://github.com/nextcloud-libraries/nextcloud-vue/assets/141107715/a0eef349-1218-4806-926e-676ce1c6fc8f)
In the screenshot above, the tool tip is displayed in English (the selected language is Slovenčina).
I have checked the [nextcloud-vue](https://github.com/nextcloud/nextcloud-vue) repository, and I found the Slovak translations are there (in sk_SK.pot file).

I checked to see whether this issue exists in other languages; I tried with Arabic, and it was working. Although I’m not certain, I suspect that issue exists for all the languages with locale-like file names that need to be mapped from language code through the ‘.tx/config’ configuration.

**Comment by susnux** [comment]
I think this is an issue with Nextcloud setting locale and language to `sk` while on nextcloud-vue `sk_SK` is used and `node-gettext´ (which is used under the hood) does not try a language fallback.
