### ISSUE TITLE
NcPopover props not fully documented

### ISSUE THREAD

**Issue by DorraJaouad** [nextcloud-libraries/nextcloud-vue#4385]
'v-bind=$attrs' could pass whatever it receives, to the child component, and there's also no link, referencing the Dropdown docs.
Further documentation should be added as Dropdown attrs are often used.

Possible solutions:

- Add a link to Dropdown $attrs https://floating-vue.starpad.dev/api/#component-props .
- Duplicate all props .
-  With Typescript - import prop interface in order to pass them into prop attributes.

**Comment by Antreesy** [comment]
Mazbe the same remark we have on DatePicker:
https://nextcloud-vue-components.netlify.app/#/Components/NcPickers?id=ncdatetimepicker
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/ce03cd5a-1c9b-4a00-aed0-ecab2a16c56f)

**Comment by ShGKme** [comment]
> Maybe, add the same remark, as we have on DatePicker: https://nextcloud-vue-components.netlify.app/#/Components/NcPickers?id=ncdatetimepicker ![image](https://user-images.githubusercontent.com/93392545/258378374-ce03cd5a-1c9b-4a00-aed0-ecab2a16c56f.png)

There is a remark:

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/e16cd308-d7a7-4883-8619-981b51d01512)
