### ISSUE TITLE
Split translations by component

### ISSUE THREAD

**Issue by susnux** [nextcloud-libraries/nextcloud-vue#4411]
I think it would be nice if we could split translations by components when building, that way not every string for even unused components end up in you bundle.

cc @ShGKme

**Comment by ShGKme** [comment]
Hmm, I didn't notice before that components with translations have all library translations. 

Indeed, if `t` is imported once in the component, then all the translations to all supported languages for all components are included:

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/0ae35219-40b4-47fc-afec-0e8564e36a9b)

**Comment by ShGKme** [comment]
Currently, we have 88 keys in translations in 106 languages which result in ~10_000 lines in each component with translations and really a lot.
