### ISSUE TITLE
[stable7] NcNavigationItem active style is broken

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud-libraries/nextcloud-vue#4418]
![Screenshot 2023-08-14 at 08 39 54](https://github.com/nextcloud-libraries/nextcloud-vue/assets/3404133/02f55027-4f8a-40aa-a0dc-c1a5f0089ec3)

Seems to happen across multiple apps on 27.1.0-beta.1

![2023-08-15 12_17_53-Recent - Nextcloud – Mozilla Firefox](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1315170/60e2bbfe-f768-429a-ad08-379c36e636b4)

So there is 
* a text styling issue for active elements and 
* a icon sytling issue for hovered expandable items

**Comment by juliushaertl** [comment]
![Screenshot 2023-08-14 at 09 12 58](https://github.com/nextcloud-libraries/nextcloud-vue/assets/3404133/acb020ba-0b90-4378-a092-c36c0aa440fa)

Strangely I cannot find this rule in stable7, only master but there also with a color-primary-element for the background color: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4155/files#diff-33b93648cb065e0fd6af0c35476aa377d217d43b8506c1ae7b3a0bb643eacc53R798-R800

**Comment by juliushaertl** [comment]
Seems that server stable27 is actually using 8.0.0-beta instead of 7.12.2 as per https://github.com/nextcloud/server/pull/39793

```
nextcloud@1.0.0 /Users/julius/repos/nextcloud/stable27
├─┬ @nextcloud/calendar-availability-vue@0.6.0-alpha1
│ └── @nextcloud/vue@7.12.2 deduped
├─┬ @nextcloud/dialogs@4.2.0-beta.2 invalid: "^4.0.0-beta.2" from the root project
│ └── @nextcloud/vue@8.0.0-beta.2    <---------------------- HERE
├─┬ @nextcloud/password-confirmation@4.0.4
│ └── @nextcloud/vue@7.12.2 deduped
├─┬ @nextcloud/vue-dashboard@2.0.1
│ └── @nextcloud/vue@3.10.2
├── @nextcloud/vue@7.12.2
└─┬ nextcloud-vue-collections@0.10.0
  └── @nextcloud/vue@3.10.2
```

**Comment by juliushaertl** [comment]
@susnux Could you maybe check that since it is coming from the dialogs bump?

**Comment by susnux** [comment]
https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/889
