### ISSUE TITLE
Please update package

### ISSUE THREAD

**Issue by eldertek** [nextcloud-libraries/nextcloud-vue#4426]
Hello, please update the package on npmjs because it says unsupported engine when installing with npm.

**Comment by ShGKme** [comment]
`master` branch with `@nextcloud/vue@8` is supposed to be used with Node LTS: `Nodejs v20`. If you have a warning here using not `Node v20` you should upgrade your nodejs to LTS.

`stable7` branch with `@nextcloud/vue@7` is supposed to be used with `Nodejs v16`. But I think we can change it to add node 18 and node 20 support, both should work.

Most of the other warnings most likely come from other packages. They should be published, but their warnings are not related to this repository.

**Comment by eldertek** [comment]
I tried to install with npm ` npm install -D @nextcloud/vue@8` but I got :
No matching version found for @nextcloud/vue@8.

**Comment by eldertek** [comment]
Also tried to install : https://www.npmjs.com/package/@nextcloud/vue/v/8.0.0-beta but I keep getting unsupported engine ([node 16 required ](required: { node: '^16.0.0', npm: '^7.0.0 || ^8.0.0' })

**Comment by ShGKme** [comment]
> I tried to install with npm ` npm install -D @nextcloud/vue@8` but I got :
> No matching version found for @nextcloud/vue@8.

`@nextcloud/vue@8` is not yet published as the `latest` release and is still in `beta` (aka `next` version). If you want to install a beta (next) version, you need to run

```sh
npm install @nextcloud/vue@next
# or a specific version
npm install @nextcloud/vue@8.0.0-beta.2
```

If you want the current latest (stable) version (`7`), you can install it without specifying the version.
```sh
npm install @nextcloud/vue
```

**Comment by eldertek** [comment]
Thank you for your explanation !
