### ISSUE TITLE
NcNavigation - Close/Open Button

### ISSUE THREAD

**Issue by eldertek** [nextcloud-libraries/nextcloud-vue#4433]
Hello, there is an issue with the close/open button since 8, I can't click on after being closed.

7.12.2 : 
![7 12 2](https://github.com/nextcloud-libraries/nextcloud-vue/assets/118362885/72099081-c9bf-424f-81ec-e2b7ee9b07e9)

8.0.0-beta.3:
![8 0 0-beta 3](https://github.com/nextcloud-libraries/nextcloud-vue/assets/118362885/0f544f99-2ed9-4b08-9f28-9cb3726b0402)

**Comment by ShGKme** [comment]
Regression of https://github.com/nextcloud-libraries/nextcloud-vue/pull/3114

`NcAppNavigation` has disabled user interaction when closed with new `inert` while the open button is also a part of it

**Comment by ShGKme** [comment]
It seems to me that it is not possible to disable `inert` for an element inside active `inert`. So we need to move the button out of navigation or use other approach rather than `inert` 😓

**Comment by eldertek** [comment]
> It seems to me that it is not possible to disable `inert` for an element inside active `inert`. So we need to move the button out of navigation or use other approach rather than `inert` 😓

It is crucial to have a solution to the issue :/
