### ISSUE TITLE
`NcRelatedResourcesPanel` click on resourse within one provider reloads a page

### ISSUE THREAD

**Issue by Antreesy** [nextcloud-libraries/nextcloud-vue#4537]
### Issue description
`<NcResource/>` renders as a `<NcButton/>` component with a following prop:
https://github.com/nextcloud-libraries/nextcloud-vue/blob/a0d027229b5ae57d9c9fb6ce61e219e87b7c6d30/src/components/NcRelatedResourcesPanel/NcResource.vue#L28

which transforms it to a `<a/>` link. Thus, if you click on a `<conversation_name>` button inside of Talk app (Shared items tab), it reloads page, instead of switching conversation

### Possible solution
`<NcButton/>` has a support of using `<RouterLink/>` with `to` prop, so could be done with a check, that global prop `providerId` matches with resource field `providerId` (and matches 'talk', if it's the only case for Talk app)

**Comment by Pytal** [comment]
Proposed solutions sounds good :)

Would this implementation be useful in files @skjnldsv and deck @juliushaertl as well?

**Comment by skjnldsv** [comment]
Not sure I get the context? :thinking:

**Comment by Antreesy** [comment]
So, in two words, this component shouldn't reload a page, when click on different conversation:
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/7b4ee542-897c-4f77-a373-d1e402ce2432)

It is used only in Deck atm, if I get it correct:
https://github.com/nextcloud/deck/blob/e8dd28752867acde15944e4d00c53caeb6570e3f/src/components/board/SharingTabSidebar.vue#L79

**Comment by skjnldsv** [comment]
The only thing I could think of is creating a global router that plugs into various apps to see if a clicked link does have a router match somewhere and if so, catch the page refresh. :thinking:

**Comment by Pytal** [comment]
> The only thing I could think of is creating a global router that plugs into various apps to see if a clicked link does have a router match somewhere and if so, catch the page refresh. 🤔

The intention was to scope this per app I believe

> It is used also only in Deck atm, if I get it correct: [nextcloud/deck@`e8dd287`/src/components/board/SharingTabSidebar.vue#L79](https://github.com/nextcloud/deck/blob/e8dd28752867acde15944e4d00c53caeb6570e3f/src/components/board/SharingTabSidebar.vue#L79)

The files panel is registered in the related_resources app itself https://github.com/search?type=code&q=org%3Anextcloud+%22NcRelatedResourcesPanel%22 fyi @Antreesy

**Comment by skjnldsv** [comment]
> The intention was to scope this per app I believe

But the NcResource.vue is standalone, no?
Might be worth thinking about this :shrug:

**Comment by Antreesy** [comment]
> The only thing I could think of is creating a global router

If that also helps to cover such app parts and cases, as UnifiedSearch / internal links in Talk messages, I'd like to try it out

Otherwise, and for that particular case, I think, 5 lines of changes locally would be sufficient

**Comment by Antreesy** [comment]
Fixed by https://github.com/nextcloud-libraries/nextcloud-vue/pull/5282
