### ISSUE TITLE
Translation updates in Transifex are not updated to the 'nextcloud-vue' translation files

### ISSUE THREAD

**Issue by vishnu-n23** [nextcloud-libraries/nextcloud-vue#4538]
The "nextcloud-vue" translation files are not updated with Transifex's translation updates. I observed this issue with Slovak translation files. The "nextcloud-vue" repository has still not reflected the changes made in Transifex before two months.

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/141107715/7098b0bb-1f66-4faf-9e78-510fb61f9f27)
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/141107715/5ae99f76-f30a-4149-9657-8e141146cd7e)

**Comment by susnux** [comment]
I can confirm there are no translation updates since a few month, something configured wrongly on transifex?
cc @skjnldsv @nickvergessen

**Comment by skjnldsv** [comment]
Should be done, let's wait for the auto sync now

**Comment by skjnldsv** [comment]
https://github.com/nextcloud-libraries/nextcloud-vue/pull/4597

**Comment by nickvergessen** [comment]
Since this was done, the duplicated resources are apparently back. Reported by @rakekniven  and on transifex.

**Comment by nickvergessen** [comment]
So I guess we need to disable the other project?

Which one did you touch @skjnldsv

**Comment by skjnldsv** [comment]
I just changed the repos on transifex

**Comment by nickvergessen** [comment]
![grafik](https://github.com/nextcloud-libraries/nextcloud-vue/assets/213943/1c26f5b7-3c96-40d1-ba45-167daaf4dcf4)

**Comment by nickvergessen** [comment]
So basically we just need to make sure the July one gets disabled I guess.

**Comment by nickvergessen** [comment]
Will try to find a way

**Comment by nickvergessen** [comment]
yeah, the second one is `nextcloud/nextcloud-vue` repository (old), the other one is `nextcloud-libraries/nextcloud-vue` (new)

**Comment by nickvergessen** [comment]
I disabled it for now, so that translators can maybe still look up how things were translated

**Comment by susnux** [comment]
See also https://github.com/nextcloud-libraries/nextcloud-vue/issues/4548

Apparently only master works but not stable7?

**Comment by nickvergessen** [comment]
> Apparently only master works but not stable7?

Yeah, totally aware, the github integration can only handle a single branch I think. At least I found no setting for branches

**Comment by nickvergessen** [comment]
> At least I found no setting for branches

https://help.transifex.com/en/articles/7130817-working-with-github-bitbucket-gitlab-branches

We can unluckily not have it because we are on the opensource plan

**Comment by nickvergessen** [comment]
![grafik](https://github.com/nextcloud-libraries/nextcloud-vue/assets/213943/4da37aea-3125-4c49-abb0-b3e3a696b1a0)


Renamed the old resource and disabled translating. So should be good now.

**Comment by skjnldsv** [comment]
> > Apparently only master works but not stable7?
> 
> Yeah, totally aware, the github integration can only handle a single branch I think. At least I found no setting for branches

paid feature
