### ISSUE TITLE
Translations in Nextcloud vue components are not working

### ISSUE THREAD

**Issue by vishnu-n23** [nextcloud-libraries/nextcloud-vue#4548]
Translations in Nextcloud-vue components are not working for the Slovak language; none of the strings in the components are being translated to Slovak. I'm using Nextcloud version v27.1.0 and Nextcloud-vue components library version v7.12.5. I reported this issue in #4384 ; it is marked as fixed on the issue page, but the issue still exists in the latest release( v7.12.5).

**Comment by susnux** [comment]
CC @nickvergessen 

Is there some transifex configuration missing for the stable7 branch?

**Comment by nickvergessen** [comment]
https://help.transifex.com/en/articles/7130817-working-with-github-bitbucket-gitlab-branches

We can unluckily not have it because we are on the opensource plan
