### ISSUE TITLE
NcAppNavigationNew should be primary instead of secondary

### ISSUE THREAD

**Issue by dartcafe** [nextcloud-libraries/nextcloud-vue#4551]
Nearly all apps use the `type="primary"` of the creation buttons inside the navigation, so `NcAppNavigationNew` should use primary too or at least support the `type` attribute of the `NcButton` component.

**Comment by susnux** [comment]
CC design team @jancborchardt @marcoambrosini

**Comment by jancborchardt** [comment]
Yep, the one main "+ New" button should always be primary. Also looking at the example from Polls which @dartcafe linked. :)
