### ISSUE TITLE
[RFC]: NcInputField - visible inner label inside input

### ISSUE THREAD

**Issue by ShGKme** [nextcloud-libraries/nextcloud-vue#4582]
With new input labels, there are two design problems:

1. It has a lower height to have space for a label on the border. It makes it smaller than other clickable elements, smaller than the required minimal clickable area, and not in line with buttons and other clickable elements:
   ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/f5f32184-db78-4eb6-97ef-3e0ccf8c28d6)
2. It doesn't look good on different backgrounds, which makes it not recommended to use when the background doesn't match (described in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4578)
   ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/546fec8a-1901-4945-b623-bd99a509dcbb)

There was another proposal for a visible label, described in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4287, that was closed in favor of https://github.com/nextcloud-libraries/nextcloud-vue/pull/4394

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/6e7169e5-5da0-4bee-be86-4f6863d0e659)

Having these issues with MD-like labels in apps, what do you think about considering returning to the first proposal?

**Comment by susnux** [comment]
I personally like both versions.

But I think the first approach is less error prone, as you do not have to think about any problems with the background where you use the components.
Moreover the outline / border-box is more clear as what you see is the outline and the label is only moved within the borders.

---

But as with the initial discussion, this is a design decision so **cc** @jancborchardt @nimishavijay @marcoambrosini

**Comment by jancborchardt** [comment]
> the first approach is less error prone, as you do not have to think about any problems with the background where you use the components.

Agree with this assessment @susnux, and thanks @ShGKme for bringing this up. I would agree with switching to the first proposal as it will look much better in all sorts of environments.

**Comment by marcoambrosini** [comment]
Back then I raised concerns about the readability of the text. The label is almost tangent to the border and might break line height accessibility requirements. And padding around input text is very little. I think that the readability of both input text and label text is more important than this background edge case.

@jancborchardt You can get a sense for it in the action menu here https://github.com/nextcloud-libraries/nextcloud-vue/pull/4287#issue-1779436635

**Comment by marcoambrosini** [comment]
The clickable area of elements doesn't have to be 44px to meet the aria AA target size success criterion.  The line height of the text needs to be at least 1.5 though.

**Comment by susnux** [comment]
> The clickable area of elements doesn't have to be 44px to meet the aria AA target size success criterion.

But for AAA. But also important: Unify element height. 

> The line height of the text needs to be at least 1.5 though

No it is not necessary, WCAG only defines this gor text blocks to help reading it. For this element we just need to ensure the padding to the bottom.

So 13px label + 7px padding + 15px text = 35px height.
So there are still  4px for borders (= 39px) and 5px additional padding for label top and bottom.

But as I said we should unify the height. NcSelect is even more height.

**Comment by marcoambrosini** [comment]
There is no need to unify the height of buttons and inputs, it might be convenient, yes, but it's by no means a priority. So I don't agree that we *should* unify the height. Text readability is far more important. No major UI library seems to be bothered with equalizing button height with input height.

If we really want to move to the inner label, I think we should go above 50px height like in the previous examples

**Comment by susnux** [comment]
We can unify with NcSelect, then it even works for a11y:
![Screenshot_20231012_172812](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/aef22119-37c9-4444-b4a0-44e7bd3110a8)

This has a height of 48px like NcSelect. This way it looks consistent when using input + select.
And even fit in the table rows (files etc) which have a height of 50px.

**Comment by marcoambrosini** [comment]
It looks better now, but I still think the other option looks better while using considerably less space. 
Let's wait for another @jancborchardt  @szaimen @nimishavijay to read this thread and share their thoughts.

**Comment by susnux** [comment]
>  Let's wait for another to read this thread and share their thoughts.

Sure :)

For testing you can find the old proposal with the inner label in branch `feat/nciputfield-v2`

> [...] while using considerably less space.

BTW the reason why I prefer unify the height of *input* elements are forms where you have multiple components, they look odd if the height does not match:

![Screenshot_20231013_182957](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/2af91792-dd19-4aca-9c03-ac5598fafbf3) | ![Screenshot_20231013_183157](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/7a6a59ce-ebbb-4485-9054-444dc2e817aa)
---|---

*(Of course the inner label is missing on the select, but even if it would also support it, the height would not match.)*

**Comment by JuliaKirschenheuter** [comment]
Dear @jancborchardt / @marcoambrosini, @nimishavijay,

i would vote for unifying the height of input elements. Would you have any points against that? 

Dear design team, we have to move forwards on our a11y issues and need a decision asap. Please give us a feedback how could we move forwards 🙏. Thanks a lot!

**Comment by szaimen** [comment]
> Dear @jancborchardt / @marcoambrosini, @nimishavijay,
> 
> i would vote for unifying the height of input elements. Would you have any points against that?
> 
> Dear design team, we have to move forwards on our a11y issues and need a decision asap. Please give us a feedback how could we move forwards 🙏. Thanks a lot!

I still think that having thr label in the border looks better but of coure having the same height for select and input field also makes sense. I guess we cannot reduce the height of the select component to match the input field? If so I am fine with this change 👍

**Comment by ShGKme** [comment]
> I still think that having thr label in the border looks better

In this case, how should be work with different backgrounds? For example, on the login page (not the only one example).

**Comment by szaimen** [comment]
> In this case, how should be work with different backgrounds? For example, on the login page (not the only one example).

There a input field with label outside should be used IIRC. cc @nextcloud-libraries/designers on this

**Comment by susnux** [comment]
If we make NcSelect smaller, we do not gain anything. It still looks weird then because the outline might match but the label on the border will not.

I think the simplest solution would be the label within and make input fields the same height as NcSelect.
This way we solve multiple problem (background colors, height issues, text height issues, clickable area for AAA) and it will look better even with a label next to a NcSelect.

(I think the problem from design perspective (at least for me) is that the label on the border is a new design element and will always look odd compared to other components, either they need this option too or no border label is used when next to an other element. The inner label does not have this problem because the border is "not broken" so if both are the same height they still match visually)

**Comment by ShGKme** [comment]
By the way, does the current solution fit AAA requirements about text readability, text height/spacing?

**Comment by JuliaKirschenheuter** [comment]
> By the way, does the current solution fit AAA requirements about text readability, text height/spacing?

I'm not an expert, but that seems (okay). Could be better, but it is readable:

![Screenshot from 2023-10-23 09-19-32](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/799630d8-4231-4a33-8a22-1a3e61daa04d)

**Comment by JuliaKirschenheuter** [comment]
But there is some other problem: if label is not visible (case where input field is empty):

![Screenshot from 2023-10-23 09-26-08](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/1c16d3d8-340c-466b-9656-e6ae0d6f8717)

**Comment by ShGKme** [comment]
> > By the way, does the current solution fit AAA requirements about text readability, text height/spacing?
> 
> I'm not an expert, but that seems (okay). Could be better, but it is readable:

By the current I meant - in the `@nextcloud/vue`'s master

**Comment by JuliaKirschenheuter** [comment]
> By the current I meant - in the @nextcloud/vue's master

No, because of this problem: https://github.com/nextcloud/server/issues/36977#issuecomment-1753137727

**Comment by marcoambrosini** [comment]
We just talked about this in the design meeting and we will go with the last version by @susnux  (48px) :)

**Comment by JuliaKirschenheuter** [comment]
@marcoambrosini, @jancborchardt, @nimishavijay 

would you approve a current state?
![Peek 2023-10-24 15-28](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/3b815079-0f76-482e-9609-db9fae69f2c1)

**Comment by ShGKme** [comment]
> We just talked about this in the design meeting and we will go with the last version by @susnux (48px) :)

@marcoambrosini Do you think we should make an optional behavior to return the previous or "small" layout? 

Or it fits fine most of the usages? I'm a bit afraid of layouts that might have counted on this size.

For example, what this place in apps' navigation should look like?

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/5a324042-3b45-46ea-80ba-f79f7923e5ba)

**Comment by susnux** [comment]
> For example, what this place in apps' navigation should look like?

This part is already custom styled, the input was sized to 44px instead of 36px and made much rounder

**Comment by marcoambrosini** [comment]
> This part is already custom styled, the input was sized to 44px instead of 36px and made much rounder

That's 36px


> Would you approve a current state?

@JuliaKirschenheuter the label needs to be vertically centered in the input when the input is not active

**Comment by marcoambrosini** [comment]
...actually, here's one last proposal keeping the current style but bringing it up to 44px (input size not counting label) and bringing the select size down to 44px too. 
As said yesterday, forms should in general be on "main" backgrounds and the login is an edge case that can be handled separately. I included a "darker" background version which doesn't look bad at all.

<img width="1075" alt="Screenshot 2023-10-25 at 14 54 55" src="https://github.com/nextcloud-libraries/nextcloud-vue/assets/26852655/94d00794-2cdc-416c-af47-6a4e78443127">

**Comment by JuliaKirschenheuter** [comment]
Hi @marcoambrosini,

Thank you for your anwer! But i disageree with you in that point:

> There's no accessibility issue whatsoever with the current input, just saying this for the record because it seemed yesterday that @jancborchardt and @JuliaKirschenheuter thought there were.

Please look in the truncation problem here https://github.com/nextcloud/server/issues/36977#issuecomment-1753137727. And this is an accessibility problem. _It must be checked whether changing text spacing leads to text truncation, overlap, or loss of functionality._

**Comment by JuliaKirschenheuter** [comment]
> ...actually, here's one last proposal keeping the current style but bringing it up to 44px (input size not counting label) and bringing the select height back down to 44px too. As said yesterday, forms should in general be on "main" backgrounds and the login is an edge case that can be handled separately. I included a "darker" background version which doesn't look bad at all.
> 
> <img alt="Screenshot 2023-10-25 at 14 54 55" width="1075" src="https://user-images.githubusercontent.com/26852655/277888279-94d00794-2cdc-416c-af47-6a4e78443127.png">

Could we please transfer it to another improvement issue?

**Comment by marcoambrosini** [comment]
>Please look in the truncation problem here https://github.com/nextcloud/server/issues/36977#issuecomment-1753137727

That is a separate issue @JuliaKirschenheuter and has nothing to do on whether we go with contained label vs label on border

**Comment by JuliaKirschenheuter** [comment]
> That is a separate issue @JuliaKirschenheuter and has nothing to do on whether we go with contained label vs label on border

It has. Please compare truncation:

|  After   | Before                                                        |
|-------------|---------------------------------------------------------------|
| ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/d961ba71-57f7-460a-86c1-2c07a0a690a0) | ![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/6078378/dd2abb45-d648-4a52-bdad-9b0798243c51)

**Comment by susnux** [comment]
> As said yesterday, forms should in general be on "main" backgrounds and the login is an edge case that can be handled separately.

That is not fully true, yes the login is - together with the dashboard widgets - an edge case. But we quite often have at least a darker background. E.g. the hover state (user list rows) etc.

So we are not really independent to the background

**Comment by marcoambrosini** [comment]
>It has. Please compare truncation:

There's some container clipping going on there and this issue is really not about that @JuliaKirschenheuter. That can happen with both designs and can be solved independently from the path we take.

> E.g. the hover state 

Text inputs should not be within elements that one can click on in the first place, so there should be no hover state background change surrounding them.

**Comment by JuliaKirschenheuter** [comment]
Ok, which way should be finally go?

**Comment by marcoambrosini** [comment]
I'm stepping back for good after that final proposal, Jan will weigh in with a final decision soon. The truncation of the component can be solved regardless of the outcome of the issue.

**Comment by jancborchardt** [comment]
Ok, spacing-wise, @marcoambrosini's latest proposal looks much better indeed. It's not as big and jarring. Let's go for this.

For the truncation issue, we need to make sure the label container is big enough and/or the text label is is centered. As @marcoambrosini said this can/must be solved independently of the overall solution.

@marcoambrosini can you please stay on this to help with the CSS details?

**Comment by JuliaKirschenheuter** [comment]
@marcoambrosini can we close this issue as https://github.com/nextcloud-libraries/nextcloud-vue/pull/4718 is merged?

**Comment by marcoambrosini** [comment]
> @marcoambrosini can we close this issue as https://github.com/nextcloud-libraries/nextcloud-vue/pull/4718 is merged?

Yes!
