### ISSUE TITLE
IDE / JEST fail to parse some CommonJS files

### ISSUE THREAD

**Issue by Antreesy** [nextcloud-libraries/nextcloud-vue#4592]
Noticed when tried to bump library from 7.12.5 to 8.0.0.beta-7

* Some bundled files compiled with Syntax error (around block of imports, could be found by `empty css`)
  * NcHeaderMenu.cjs
  * NcAppNavigationSettings.cjs
  * NcListItemIcon.cjs
* Replacing comma with semocolon resolves problem

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/248418c5-7837-4176-ad40-24d53bca0036)

**Comment by susnux** [comment]
Seems to be a problem of esbuild minify and the vite css plugin, see https://github.com/vitejs/vite/issues/14515

**Comment by susnux** [comment]
I create a PR for a work-around (just skip minify any whitespace, like we do for esm).
