### ISSUE TITLE
NcModal close button is inaccessible with scrollable content

### ISSUE THREAD

**Issue by Antreesy** [nextcloud-libraries/nextcloud-vue#4627]
Issue:
- Probably a regression from #4350
- After re-ordering of DOM elements `modal-container__close` and `modal-container__content` content can overlap close button, making it inaccessible

Screenshots:
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/fd075676-5eff-4289-8c58-57254bcc8bdd)
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/5ca5af01-50e9-4b4c-80a0-9ced3f305f83)

Possible solution:
- set `z-index: 1` for `modal-container__close`

_Originally posted by @Antreesy in https://github.com/nextcloud-libraries/nextcloud-vue/issues/4350#issuecomment-1752659310_

**Comment by susnux** [comment]
BTW this is caused by talk resetting the modal content margin, normally there is a margin of 50px so there should be not content overlapping the button.
