### ISSUE TITLE
Scrollbar of `NcAppContentList` hard to catch with resizable columns

### ISSUE THREAD

**Issue by mejo-** [nextcloud-libraries/nextcloud-vue#4706]
When using resizable columns in `NcAppContent`, the scrollbar for `NcAppContent` is hard to catch with the mouse. See the screencast:

## Screencast
[recording1.webm](https://github.com/nextcloud-libraries/nextcloud-vue/assets/3582805/48b67c6a-e0cf-4e96-b6dc-a313b6fa81cf)

My suggestion would be to change the scrollbar width from `thin` to normal if the `NcAppContent` columns are resizeable.

@jancborchardt @nimishavijay for design team input.

**Comment by mejo-** [comment]
By the way, this problem only exists in Firefox. In Chrome, the scrollbar is much wider.

**Comment by nimishavijay** [comment]
> My suggestion would be to change the scrollbar width from thin to normal if the NcAppContent columns are resizeable.

Sounds good to me! :)
