### ISSUE TITLE
NcNoteCard doesn't get the info type

### ISSUE THREAD

**Issue by zak39** [nextcloud-libraries/nextcloud-vue#4749]
Hi everyone :wave: 

I'm working on the workspace app and I would like to implement the NcNoteCard as a info type.

```html
		<NcNoteCard v-if="$route.params.group && addingUsersToWorkspace"
			type="info">
			<p>
				{{ t('workspace', 'Caution, users highlighted in red are not yet member of this workspace. They will be automaticaly added.') }}
			</p>
		</NcNoteCard>
```

Even though, when I see the component from browser, it doesn't get the info type :point_down: 

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/28636549/e093b548-8fb9-4b8a-8c61-4f01714b4376)

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/28636549/c73a8947-ecd8-48e7-bba4-a5a2379893a4)

if you need, here is my package.json : https://github.com/arawa/workspace/blob/main/package.json

**Comment by dartcafe** [comment]
I would wish it to land in the 7.x version too, but it seems it is introduced with the 8.x version.

**Comment by ShGKme** [comment]
> if you need, here is my package.json : https://github.com/arawa/workspace/blob/main/package.json

You are using `@nextcloud/vue 7` while this feature was added in `@nextcloud/vue 8`
