### ISSUE TITLE
NcInputField design issues

### ISSUE THREAD

**Issue by susnux** [nextcloud-libraries/nextcloud-vue#4766]
Follow up on #4718 

- [ ] Fix alignment of trailing button
- [ ] Fix alignment of placeholder text

---
The trailing button, e.g. the "clear content" or "show password" button, are not centered at the moment:
![](https://user-images.githubusercontent.com/1855448/281009804-fcea6507-2d6a-432e-96e5-d7c7331e94e7.png)

The placeholder text is currently not correctly centered:
![](https://user-images.githubusercontent.com/6078378/281014170-4076ec45-be2a-41c6-9032-4db39b973f88.png)

**Comment by ShGKme** [comment]
Should overflowing of a label be considered a component's issue?
Like on the screenshot with the grid.

**Comment by susnux** [comment]
> Should overflowing of a label be considered a component's issue?

Is ellipsis an issue? Even if we provide a title attribute with the full label?
