### ISSUE TITLE
NcAppSettingsDialog is not working properly on nc/vue 8.0.0

### ISSUE THREAD

**Issue by GretaD** [nextcloud-libraries/nextcloud-vue#4782]
I changed the `:title` to `:name`. The navigation is shown on top instead of left, and this error popsup

![Screenshot from 2023-11-08 18-07-59](https://github.com/nextcloud-libraries/nextcloud-vue/assets/12728974/4c397fbc-2b45-4be5-886a-621fe9ccc158)

**Comment by ShGKme** [comment]
I haven't tested, but it seems that the contacts app uses an old `"vue": "~2.6.14"` while `@nextcloud/vue@8` requires Vue 2.7.

Vue 2.6 doesn't support many new features, including reactivity functions and Composition API. While it is supposed to be handled by `vue-demi`, it might have be the source of the issue.

Try to upgrade Vue to 2.7.

**Comment by GretaD** [comment]
you're right, upgrading and removing https://github.com/vuejs/composition-api fixed the issue
