### ISSUE TITLE
[8.0.1] Sidebar vanishes out of viewport after adding an element to content

### ISSUE THREAD

**Issue by dartcafe** [nextcloud-libraries/nextcloud-vue#4802]
Version 8.0.1, Nextcloud 28.0.0 beta 1

When adding an element to the sidebar view the content partially gets moved out of the viewport. In this case an input field is added (via `v-if`) below the clicked toggle. Resizing the window brings the sidebar back to the viewport partially. You can check it with the current beta of polls.

**Edit:** The behavior alters with different window heights. This only happens, if the position of change is not in the initial viewport. I have to scroll to the position, where the element is added, to provocate this behavior. 

Adding vote limit | resizing afterwards
-|- 
https://github.com/nextcloud-libraries/nextcloud-vue/assets/26707476/30a7b511-3bd0-485b-8d63-914ac327cbea | https://github.com/nextcloud-libraries/nextcloud-vue/assets/26707476/249df834-d2e9-4d8d-b06b-d0eaa7c0256f 

(videos duplicated since they seem not to be displayed inside the table)

https://github.com/nextcloud-libraries/nextcloud-vue/assets/26707476/30a7b511-3bd0-485b-8d63-914ac327cbea

https://github.com/nextcloud-libraries/nextcloud-vue/assets/26707476/249df834-d2e9-4d8d-b06b-d0eaa7c0256f

**Comment by dartcafe** [comment]
@szaimen I need help. I have no idea, what happens here. The DOA for the version 28 is not far away, and this issue makes the app unusable. Any hint, what I could have done wrong? I can't see, what is causing this behavior. Pre 8.x the sidebar behaved normally.

**Comment by szaimen** [comment]
> @szaimen I need help. I have no idea, what happens here. The DOA for the version 28 is not far away, and this issue makes the app unusable. Any hint, what I could have done wrong? I can't see, what is causing this behavior. Pre 8.x the sidebar behaved normally.

I fear I dont know what causes this. Maybe @susnux or @raimund-schluessler know?

**Comment by ShGKme** [comment]
Checking

**Comment by ShGKme** [comment]
This is a regression of https://github.com/nextcloud-libraries/nextcloud-vue/pull/2776

`<input>` in `<NcCheckboxRadioSwitch>` is moved away with `position: absolute`. But it receives a focus. As a result, the sidebar tab tries to scroll to the visually hidden checkbox.
