### ISSUE TITLE
[NcSelect] Single select looks like tag select

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud-libraries/nextcloud-vue#4816]
multiple=false selects should not looks like tagging selects, but they do:

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1374172/90d54429-73b1-4656-8709-07ac9a3a6685)

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1374172/bebad8d7-988e-4592-a7dd-c87b185d7eed)

this is a regression according to @marcoambrosini

it's seen across the hub with all apps ready for server 28

**Comment by szaimen** [comment]
So what should it look like? Should we simply move back to the previous design?
It looked like this: 
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/5c65af10-d330-42e0-a928-fd6f22fe1631)
cc @nextcloud-libraries/designers

**Comment by ChristophWurst** [comment]
Try with multiselect=false

**Comment by ChristophWurst** [comment]
e.g.

| 25 | 28 |
|--------|--------|
| ![Bildschirmfoto vom 2023-11-14 14-37-43](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1374172/f341cb6a-c22f-4ac3-9960-81cd2340e5b1) | ![Bildschirmfoto vom 2023-11-14 14-37-58](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1374172/c02cb3a6-0be7-4cf4-9a12-819cf4c20322) |
