### ISSUE TITLE
NcRichContenteditable not accepting clipboard pasted text

### ISSUE THREAD

**Issue by Rello** [nextcloud-libraries/nextcloud-vue#4821]
* type a text
* paste text from clipboard
=> the new text is not included in e.g. talk posts

* add a line brake after the pasted text
=> the new text is included

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud-libraries/nextcloud-vue/assets/1580193/352cbc9e-e333-4ffb-8d15-c63f266414d4

Happens on Safari 17, works fine on Chrone

**Comment by DorraJaouad** [comment]
![pasted-text](https://github.com/user-attachments/assets/9d201665-74d8-4fe0-a23e-a2f83cee2ce1)
on Chrome
