### ISSUE TITLE
I have a problem with the sidebar, specifically the popup, when I scroll it doesn't stay.

### ISSUE THREAD

**Issue by Gibran2075** [nextcloud-libraries/nextcloud-vue#4826]
I'm using NextCloud v.22.1.1, I have to stay on this version because it's integrated with other data, can anyone help?
![Screenshot (393)](https://github.com/nextcloud-libraries/nextcloud-vue/assets/107015940/243ef5e8-8510-4b45-8453-7789974b29f1)
![Screenshot (394)](https://github.com/nextcloud-libraries/nextcloud-vue/assets/107015940/0f114ab7-6987-47c0-bb17-16659724e7fb)

**Comment by raimund-schluessler** [comment]
Your version is long out of support and you don't even use the latest minor version of v22. The issue you describe has been fixed already in later versions. You cannot expect a backport of this fix to an end-of-life version.

And, one needs to emphasize this again and again, I suppose: Running end-of-life software, especially software exposed to the web, is a terrible idea.

The only sane recommendation here is to update to the latest version, or at least to a version still supported, i.e. v26 or later.
