### ISSUE TITLE
Sidebar tab regression: Checkbox switch uses tab header styling

### ISSUE THREAD

**Issue by susnux** [nextcloud-libraries/nextcloud-vue#4847]
Regression of https://github.com/nextcloud-libraries/nextcloud-vue/pull/4815 (cc @marcoambrosini )

The deep selectors used for the tab header also broke all other NcCheckboxRadioSwitch that are used on any sidebar tab:

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/dea2dcc7-7c53-4365-a560-d68687d002a5)

**Comment by ShGKme** [comment]
Duplication of https://github.com/nextcloud-libraries/nextcloud-vue/issues/4822 and is already fixed on `master`.
