### ISSUE TITLE
Top and bottom padding of action menu too much, does not match sides

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud-libraries/nextcloud-vue#4870]
Note that the top (and bottom) whitespace in the action menu is much larger than the left and right. This didn’t happen in the previous release and looks off:
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/925062/3a48c03d-f23a-43ab-a720-84e43c14a55d)

Edit: Example of bottom padding, in Talk (same issue of course with top padding here too):
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/925062/806563ad-8cd5-4aa4-a06f-dce232a5d342)

cc @szaimen @marcoambrosini

**Comment by AndyScherzinger** [comment]
-> not blocked by feature freeze
