### ISSUE TITLE
Keyboard focus on collapsed apps menu looks weird

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud-libraries/nextcloud-vue#4890]
<img width="262" alt="image" src="https://github.com/nextcloud-libraries/nextcloud-vue/assets/1580193/f489ad1a-b564-49cb-b450-30f719a52388">

On 28 RC1. I assume this is a lib issue not a server one, but not totally sure.

1. Shrink browser width to show the "..." menu
2. Open the menu with the keyboard
3. Notice the above

**Comment by ShGKme** [comment]
I can reproduce neither in Chromium nor in Firefox. Is the screenshot from Safari?

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/1dea6df2-5125-4f94-a426-fd6c77817a18)

**Comment by ShGKme** [comment]
Oh, no, I can reproduce in Chromium now

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/28a4e24d-ac6b-419b-8f84-798c51dc5471)
