### ISSUE TITLE
NcSelect Timezone picker breaks on Firefox when using with NcPopover

### ISSUE THREAD

**Issue by miaulalala** [nextcloud-libraries/nextcloud-vue#4917]
Since the component uses a manual z-index, the component looks like this on Firefox when using it together with the NcPopover 

https://github.com/nextcloud/calendar/issues/5606

**Comment by susnux** [comment]
It does not have any custom stylings so this is caused by NcSelect which is used under the hood.

**Comment by miaulalala** [comment]
The code is here: https://github.com/nextcloud/calendar/blob/baeeae244614586bbc3c1efd3233f26a84ec0a01/src/components/Shared/DatePicker.vue#L63

**Comment by st3iny** [comment]
That seems to be it. hanks again @susnux :heart:
