### ISSUE TITLE
NcDialog: Padding not applied correctly

### ISSUE THREAD

**Issue by Chartman123** [nextcloud-libraries/nextcloud-vue#4977]
https://github.com/nextcloud-libraries/nextcloud-vue/blob/c8da0f46079abaca06f31017e6be5d564f901ade/src/components/NcDialog/NcDialog.vue#L393-L394

The padding specified in the above rules is not applied correctly. To solve this problem `!important` should be added to those two lines.

**Comment by susnux** [comment]
`!important` should be avoided where possible to allow users of the library to override the styles if needed (e.g. the filepicker in this case)

**Comment by ShGKme** [comment]
Isn't it fixed by 
- https://github.com/nextcloud-libraries/nextcloud-vue/pull/4897
?

**Comment by Chartman123** [comment]
Is this already in release? If not, yes this should probably fix it...

**Comment by ShGKme** [comment]
> Is this already released? If not, yes this should probably fix it...

Not yet.

**Comment by susnux** [comment]
Is fixed with the latest release at least it looks correct, reopen if I am wrong.
