### ISSUE TITLE
Dead Links in Developer Manual

### ISSUE THREAD

**Issue by DrAxelbauer** [nextcloud-libraries/nextcloud-vue#4982]
Hi there!
I just came across some dead links and wanted to let you know.
I tried to find the Vue code for the ActionMenu in NC via:
[https://docs.nextcloud.com/server/latest/developer_manual/design/atomiccomponents.html#action-menu](url)

But that leads to a dead end:
[https://nextcloud-vue-components.netlify.app/#/Components/Actions](url)

Where can I find the directives about the ActionMenu?

**Comment by ShGKme** [comment]
> Where can I find the directives about the ActionMenu?

https://nextcloud-vue-components.netlify.app/#/Components/NcActions
