### ISSUE TITLE
[next] Release `9.0.0-alpha.0`

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud-libraries/nextcloud-vue#5043]
I think it is time for an `alpha` release of `nextcloud/vue@9.0.0`. What do you think @skjnldsv @ShGKme @susnux @nextcloud-libraries/developers?

**Comment by susnux** [comment]
Sure, lets do an alpha :rocket: 

But I expect some other things to come up (for which an alpha is perfect so we get feedback) so I would expect a lot of alpha / beta releases :wink:

**Comment by raimund-schluessler** [comment]
> But I expect some other things to come up (for which an alpha is perfect so we get feedback) so I would expect a lot of alpha / beta releases 😉

Definitely, we will see a lot of pre-releases, I guess. But that's what they are there for 🤷 Having a release on NPM will also allow us to test the automated workflows of the apps using the library, which currently fails.

Can we maybe aim for a pre-release this week? Vue 2 is EOL after all, and we should push this forward a bit.

**Comment by ShGKme** [comment]
@raimund-schluessler I'll prepare the release later today

**Comment by raimund-schluessler** [comment]
@ShGKme Great! Thanks a lot. Could we just merge https://github.com/nextcloud-libraries/nextcloud-vue/pull/5074 before?

**Comment by susnux** [comment]
Done with #5126
