### ISSUE TITLE
`NcDateTimePicker` week labels off by one

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud-libraries/nextcloud-vue#5044]
Originally reported in https://github.com/nextcloud/tasks/issues/2366.

See here:
![Screenshot 2024-01-09 at 13-17-51 Aufgaben - Nextcloud](https://github.com/nextcloud/tasks/assets/2496460/3a82faa5-b0c7-4317-a55d-ea1db874ed6a)

The first week of January should be the week with the starting year's first Thursday in it (the formal
ISO definition), see https://en.wikipedia.org/wiki/ISO_8601

In the screenshot above, the first week starts 7 days to early. What is labeled as `1` should be `53` of 2022.

**Comment by raimund-schluessler** [comment]
There seems to be a solution using moment.js

https://github.com/mengxiong10/vue2-datepicker/issues/679#issuecomment-1017431852

**Comment by susnux** [comment]
It can be fixed without moment -> no need for "dead" software :wink:
