### ISSUE TITLE
Multiselect placeholder translation 

### ISSUE THREAD

**Issue by Valdnet** [nextcloud-libraries/nextcloud-vue#512]
Is it possible to add translations for: "Select option" and "List is empty".
When you set your mother tongue, it looks a little strange:

![obraz](https://user-images.githubusercontent.com/47037905/61535707-3b82e980-aa33-11e9-8ef4-069d8d71dd8b.png)
---
![obraz](https://user-images.githubusercontent.com/47037905/61535871-9b799000-aa33-11e9-91d9-ed18ef3687f6.png)

**Comment by skjnldsv** [comment]
Reference: #97

**Comment by Valdnet** [comment]
@skjnldsv There is still no text string `Select option` in Transifex:

![obraz](https://user-images.githubusercontent.com/47037905/161516364-948f692f-cba8-4bba-a5a1-5713195c8b30.png)

**Comment by skjnldsv** [comment]
You need to add a support and default for placeholder
https://github.com/nextcloud/nextcloud-vue/blob/71e8f2f67b9e35e17b36287e89a1e7dd2a67c596/src/components/Multiselect/Multiselect.vue#L162

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/nextcloud-vue/blob/71e8f2f67b9e35e17b36287e89a1e7dd2a67c596/src/components/Multiselect/Multiselect.vue#L250-L255

```js
		placeholder: {
			type: String,
			default: t('Select option')
		},
```

**Comment by Valdnet** [comment]
@skjnldsv What with that: This `List is empty` text string is also not present in Transifex in Vue.

**Comment by susnux** [comment]
NcMultiselect was replaced by NcSelect which translates that string :)
