### ISSUE TITLE
[v8.x] NcNavigationNewItem: Is this an accident?

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud-libraries/nextcloud-vue#5159]
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/986878/c90c2343-9cad-4c3a-bffc-5ec95cae3e8d)

This looks terrible in the Navigation bar, imo.

**Comment by raimund-schluessler** [comment]
Yes, this is definitely a regression.

**Comment by raimund-schluessler** [comment]
Could be related to https://github.com/nextcloud-libraries/nextcloud-vue/pull/4730.

**Comment by raimund-schluessler** [comment]
@szaimen Could you have a look, please? It seems like not all review comments in #4730 got resolved before merging.

**Comment by szaimen** [comment]
This didnt break in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4730. See https://deploy-preview-4730--nextcloud-vue-components.netlify.app/#/Components/App%20containers/NcAppNavigation?id=ncappnavigationnewitem and 
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/42591237/6228b7ee-c171-4b81-854d-c41c64fdbf1d)

**Comment by raimund-schluessler** [comment]
Indeed, the preview looked fine. Weird.

**Comment by raimund-schluessler** [comment]
Seems like it was me 🙈 in #4989, sorry. I will double-check and provide a PR.
