### ISSUE TITLE
Dropdown menu renders in a wrong direction

### ISSUE THREAD

**Issue by EtagiBI** [nextcloud-libraries/nextcloud-vue#5233]
In NC Mail there's a dropdown menu for account settings. After signing up to NC Mail every user experience incorrect behavior of this menu, because the component renders upwards (partially):

Steps to reproduce:
1) Sign up to NC Mail
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/20855725/f973714e-71cb-4f4d-8197-e550dba0b79b)

2) Open account settings dropdown menu
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/20855725/ff620f63-4d89-426f-ba5e-5c3cb0cfa663)

After a couple of page reloads the component renders correctly.

**Comment by susnux** [comment]
I think this is fixed now as the container for the actions was set to the app content, so floating-ui should automatically choose the correct direction. (nextcloud-vue 8.16+)

**Comment by EtagiBI** [comment]
With nextcloud-vue 8.16 the problem is gone indeed
