### ISSUE TITLE
Link/mention picker should not pop up when typing inside a word

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud-libraries/nextcloud-vue#5351]
Try to post something like:
```
Works now in direction A/B
```

The `/` brings up the link picker:
![grafik](https://github.com/nextcloud-libraries/nextcloud-vue/assets/213943/fef3e735-1177-4bdf-ac39-f661940996ee)

Pressing `ESC` not only closes the link picker but also unfocuses the chat input of Talk.

Same happens with `@` inside words.

From my perspective it would be the best to only start the picker with a leading whitespace, linebreak, empty (beginning of message). Showing it in the middle of a word is quite annoying.

~~Should also take a look into the `ESC` handling so when it cancels Tribute, it does not additionally cancel the NcContentEditable focus.~~ moved to other issue and solved

cc @ShGKme @Antreesy

**Comment by Antreesy** [comment]
From what I see in the library code, there's no way to use regex for this as trigger for mentions. Manual trigger with `/(?:^|\s)@$/` instead of `@` doesn't seem to behave properly
One more reason to fork the lib

**Comment by Antreesy** [comment]
Regression comes with https://github.com/nextcloud-libraries/nextcloud-vue/commit/0bf2293f2eaea9722409f769d642390230dd24bd
