### ISSUE TITLE
Check widget errors

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud-libraries/nextcloud-vue#5383]
From https://github.com/nextcloud-libraries/nextcloud-vue/pull/5365
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/3404133/d550a54f-40e5-4252-a718-9d3584ee3290)
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/3404133/9f3a45d1-ba15-4635-92a4-7663d28a85a7)

**Comment by ShGKme** [comment]
And

![Uploading image.png…]()
