### ISSUE TITLE
User status broken on safari

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud-libraries/nextcloud-vue#5386]
<img width="273" alt="image" src="https://github.com/nextcloud-libraries/nextcloud-vue/assets/1580193/7cca6e6e-16e3-4164-a1b1-b78bcd762002">

Bisect on server points to lib 8.5.0 bump: https://github.com/nextcloud/server/pull/43061. Looking through the changelog https://github.com/nextcloud-libraries/nextcloud-vue/pull/5059 feels like a good candidate?!

Also happens for me on latest master of server.

CC @Pytal

**Comment by nickvergessen** [comment]
cc @Antreesy as user_status maintainer can you take a minute (and the Talk team Macbook)

**Comment by Antreesy** [comment]
Broken at the Vue styleguide as well.. Looking into it
