### ISSUE TITLE
NcDialog, NcReferenceWidget generate Vue warnings for the vueuse/core methods

### ISSUE THREAD

**Issue by Antreesy** [nextcloud-libraries/nextcloud-vue#5393]
Warning:
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/93392545/5660d56d-803e-4cb4-9aa6-8492fe2ca72d)

UPD: Looking as this also happened with NcReferenceWidget, I'd blame `useResizeObserver` => `useMounted` hook:
https://github.com/vueuse/vueuse/blob/9f10ad06a4fd2b4e6325dc72a3d1e36a62b6c254/packages/core/useResizeObserver/index.ts
https://github.com/vueuse/vueuse/blob/9f10ad06a4fd2b4e6325dc72a3d1e36a62b6c254/packages/core/useSupported/index.ts
https://github.com/vueuse/vueuse/blob/9f10ad06a4fd2b4e6325dc72a3d1e36a62b6c254/packages/core/useMounted/index.ts#L12-L17

But tracked it back to our library: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5298

**Comment by susnux** [comment]
Yes the `useResizeObserver` must be moved to the `setup`.

**Comment by Antreesy** [comment]
Doesn't explain the warnings on NcDialog rendering

**Comment by ShGKme** [comment]
> Yes the `useResizeObserver` must be moved to the `setup`.

At least in Vue 3, lifecycle hooks like `mounted` as well as `computed` also have setup context, so in general case composables works in `mounted`.

Though, I'd prefer to always use them only in the `setup`.

**Comment by susnux** [comment]
> Doesn't explain the warnings on NcDialog rendering

https://github.com/vueuse/vueuse/pull/3830

**Comment by Antreesy** [comment]
Closed with https://github.com/nextcloud-libraries/nextcloud-vue/pull/5640
