### ISSUE TITLE
NcCounterBubble just keeps counting up

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud-libraries/nextcloud-vue#5486]
We used to have a limit like 99+ or at least 999+ because after that the unread info just becomes useless. This seems to have been removed, is there any specific reason as to that?

Maybe @nickvergessen as it most prominently happens in Talk (but also would concern Mail, News, and others):

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/925062/ed047e2b-c651-4a37-9c89-d97775b58e31)

**Comment by nickvergessen** [comment]
Was 999+

**Comment by susnux** [comment]
There is no logic in the counterbubble component, it is just a stylistic wrapper. You can put any content inside it, so we can not simply parse it.

Meaning currently it is up to the component user to do something like:
```vue
<NcCounterBubble>
    {{ number > 999 ? '999+' : number }}
</NcCounterBubble>
```

But I think we also have some places where we limit it to `99+`.

**Comment by jancborchardt** [comment]
@susnux could we have this logic in the component though, so we can standardize it to 999+?
