### ISSUE TITLE
RichText causes errors on WebKit | Invalid regex

### ISSUE THREAD

**Issue by susnux** [nextcloud-libraries/nextcloud-vue#5589]
The regex for mentions is using lookbehind which is not supported on all iOS versions / Safari versions we support.
It only works on 16.4+ but we support 15+.

The problem is within the regular expression:
https://github.com/nextcloud-libraries/nextcloud-vue/blob/a2854e9cb99d0c14108180cbcee67f6240dfed70/src/mixins/richEditor/index.js#L32

**Comment by susnux** [comment]
It does not look like that. So welcome any contribution :)

**Comment by punkyard** [comment]
hi, could this issue be related? : https://github.com/nextcloud/server/issues/46525
