### ISSUE TITLE
NcButton styles missing in bundler output in 8.12

### ISSUE THREAD

**Issue by hschletz** [nextcloud-libraries/nextcloud-vue#5719]
After updating from 8.11.3 to 8.12, NcButton components in my app lack styling when built via "vite build" or "vite watch":

![8 12](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1310065/878b87db-c233-428d-ad54-b0d173978de5)

The CSS rules for the ".button-vue" selectors are missing. Output from "vite dev" is correct, and the rules exist:

![8 11 13](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1310065/37f40b27-2c30-4dad-8906-cce59ff268c7)

Downgrading to 8.11.3 temporarily fixes the problem.

Here's the vite.config.ts I used for the screenshot:

````ts
import { createAppConfig } from '@nextcloud/vite-config'
import { defineConfig } from 'vite'
import tsconfigPaths from 'vite-tsconfig-paths'

const config = defineConfig(async () => ({
    plugins: [
        tsconfigPaths(),
    ],
    resolve: {
        // Adding extensions here has no effect
        extensions: ['.js', '.ts', '.vue', '.scss'],
    },
}))

export default createAppConfig({
    // Entry points...
}, {
    config,
})

**Comment by hschletz** [comment]
I sort of found the problem, which is apparently not caused by @nextcloud/vue directly. The observed behavior is just a symptom.

My application has multiple entry points. One of them is the main application from which the screenshots were taken. Another one is a plugin for the files application which shares some dependencies with the main application. Vite splits common code into separate files which will be loaded automatically. This usually works fine.

One of those shared dependencies is @nextcloud/dialogs which both entry points use for toasts. After removing all references to this package from the files plugin, the main application displays correctly. In fact, the problem can be reproduced by any additional entry point as simple as
````js
import { showError } from "@nextcloud/dialogs"
showError('boo')
````
Using both packages in a single entry point does not cause problems.

I suspect the root cause is with @nextcloud/dialogs, which acts weirdly regarding bundling, tree shaking and code splitting.

I'm leaving this issue open in case you plan to make the package immune to interference (up to 8.11.3, this was not a problem).

**Comment by ShGKme** [comment]
Hi @hschletz 

This is a Vite's bug. We have just created a Vite plugin in our `@nextcloud/vite-config` to fix this behavior.

https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/204

It is to be released very soon.
