### ISSUE TITLE
NcAppNavigationSettings: Settings toggle button stil has `--pill` border radius

### ISSUE THREAD

**Issue by st3iny** [nextcloud-libraries/nextcloud-vue#5764]
The toggle button for the app navigation settings is still using the old `--pill` border radius. 

![Screenshot_20240703_095147](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1479486/a68b8c7a-b7e7-4690-8404-0c332f08eb42)

---

I tried to simply replace it with `var(--border-radius-element, calc(var(--default-clickable-area) / 2));` but it somehow doesn't look right.

![Screenshot_20240703_095121](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1479486/9c72697f-eb3f-488a-8c48-1bf0093eb696)

PR at https://github.com/nextcloud-libraries/nextcloud-vue/pull/5765 if you think this is good enough.

**Comment by susnux** [comment]
> I tried to simply replace it with `var(--border-radius-element, calc(var(--default-clickable-area) / 2));` but it somehow doesn't look right.

No it needs to be:
`var(--body-container-radius)`

**Comment by st3iny** [comment]
I pushed your recommendation to my PR and made it ready for review.
