### ISSUE TITLE
App navigation sub entries are not indented anymore

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud-libraries/nextcloud-vue#5798]
Sub entries such as in Files under "Favorites" and "Shares" used to be nicely indented to the right a bit. This is currently not the case, and results in a less than clear overview, so it would be nice to fix it.

Some previous release (properly indented) | Current master (no separation between main items and sub items)
-|-
![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/925062/6f843272-0548-49f7-b7f3-9be4f8c0d5fa)|![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/925062/719e99ec-88d3-4638-a314-800d38f44b97)

**Comment by susnux** [comment]
For me this works on current Nextcloud server master branch:

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/1855448/f19c85a0-562c-479c-acd8-bfebd77e925f)

**Comment by jancborchardt** [comment]
This is what I see on daily:
![image](https://github.com/user-attachments/assets/6cbd8585-cb6c-49a4-b5d2-c30f94466521)

**Comment by ShGKme** [comment]
Interesting bug. Apps loading changes the styles. Investigating...

**Comment by ShGKme** [comment]
P.S. One more example, why 2-way encapsulation `<style module>` is better than 1-way `<style scoped>` for complex platforms like Nextcloud.

**Comment by jancborchardt** [comment]
Thanks! Just closing it as completed instead of not planned. :)
