### ISSUE TITLE
License info in online docs

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud-libraries/nextcloud-vue#5808]
![image](https://github.com/user-attachments/assets/6b8adde2-ff65-4e4b-9c37-fa0b8d2f50c0)

https://nextcloud-vue-components.netlify.app/#/Components/NcActions?id=ncactionradio

This looks unintended.

**Comment by ShGKme** [comment]
Interesting... I don't understand what the difference is between components with and without SPDX in the style guide...

**Comment by ShGKme** [comment]
Affected components:
- 2020
  - `NcHeaderMenu`
  - `NcAppNavigationSettings`
- 2019
  - `NcActionCheckbox`
  - `NcActionInput`
  - `NcActionLink`
  - `NcActionRouter`
  - `NcActionRadio`
  - `NcActionText`
  - `NcActionTextEditable`
  
Interesting facts:
- Year in the styleguidist has no relation to the year in the component's SPDX comment. 
- Removing docs or SPDX comment doesn't fix the problem

**Comment by ShGKme** [comment]
How to reproduce:
1. Add any mixin with JSDoc to a component
2. See mixin's JSDoc in the styleguide

**Comment by ShGKme** [comment]
Proposal: get rid of mixins 💃

**Comment by ShGKme** [comment]
There is [validExtends](https://vue-styleguidist.github.io/Configuration.html#validextends) config, that disables this feature. But this would also disable parsing props in many `NcAction*` using `actionText` mixin.
