### ISSUE TITLE
NcInputField should be submitted when using the Enter key

### ISSUE THREAD

**Issue by GVodyanov** [nextcloud-libraries/nextcloud-vue#5824]
Due to using the `@trailing-button-click` to submit the input, hitting the <kbd>Enter</kbd> key doesn't do anything, as it should in my opinion.

Also, due to the custom event, using min-length doesn't work, and you have to check whether there are any characters inputted in the triggered method.

Somewhat relevant to https://github.com/nextcloud/contacts/pull/4039

**Comment by ShGKme** [comment]
`submit` is an event of a `form` element, not an `input` element. So using <kbd>Enter</kbd> for submitting is a form's feature.

`trailing-button-click` doesn't always mean "submit". It might be "clear", for example.

If we want to add an ability to submit by trailing button, we may add a way to provide `nativeType` to `NcButton` of the trailing button. Then we can use submit natively.

**Comment by ShGKme** [comment]
Closing. Feel free to reopen if still actual or there are new thoughts
