### ISSUE TITLE
NcSelect jumps/resizes on focus

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud-libraries/nextcloud-vue#5874]
| Default | Focus |
|--------|--------|
| ![Bildschirmfoto vom 2024-07-26 11-38-29](https://github.com/user-attachments/assets/51029fa8-a087-49e6-a902-09527538a94a) | ![Bildschirmfoto vom 2024-07-26 11-38-32](https://github.com/user-attachments/assets/aade426d-3556-4a24-908e-37e685f68c8d) | 

Look at the elments below. They are pushed down.

The default border is thinner than the focus border. Do we need a negative margin of the diffence between the two borders? E.g. if the default border is 1px and focus is 2px, the element has to move up by 1px to make up for the increased size, and everything will stay at its place regardless of focus state.

**Comment by ChristophWurst** [comment]
@jancborchardt could you discuss this with your designers?

**Comment by jancborchardt** [comment]
@marcoambrosini @susnux @ShGKme this also came up in a design review. How do we best fix this?

**Comment by ShGKme** [comment]
> @marcoambrosini @susnux @ShGKme this also came up in a design review. How do we best fix this?

Do you have it on the current `@nextcloud/vue` version?

**Comment by ChristophWurst** [comment]
Confirm it to be fixed via https://nextcloud-vue-components.netlify.app/#/Components/NcSelect
