### ISSUE TITLE
Wrong radiuses for radio switch component

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud-libraries/nextcloud-vue#5875]
![image](https://github.com/user-attachments/assets/69b9973e-ae4a-4f18-a964-34b94ecc76e4)

It should use the element radius in Nextcloud 30+.

cc @jancborchardt @marcoambrosini

**Comment by jancborchardt** [comment]
@marcoambrosini can you look into that?

**Comment by marcoambrosini** [comment]
Yep, I was tackling that here https://github.com/nextcloud-libraries/nextcloud-vue/pull/5923

**Comment by ShGKme** [comment]
Sorry 🙈
- Missed this issue when checked https://github.com/nextcloud/server/issues/46016
- Fixed by https://github.com/nextcloud-libraries/nextcloud-vue/pull/5974
