### ISSUE TITLE
Datepicker header a bit confusing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud-libraries/nextcloud-vue#817]
You want to change to the next month, which button do you click?
![datepicker header complicated and bug](https://user-images.githubusercontent.com/925062/72388453-4be7f880-3726-11ea-966f-dc5d18dc2b6b.png)

It’s confusing. There is a very simple way of switching the years by clicking on the year already.

So we can simplify to a single forward arrow and backward arrow which would switch the months only.

(Also the vertical alignment is off a bit.)

cc @georgehrke

**Comment by georgehrke** [comment]
cc @skjnldsv

**Comment by georgehrke** [comment]
I'm not sure how far we can customise it. We are still using version 2 of `vue2-datepicker` and there is a major update to version 3 available. Let's update to 3 first and afterwards see what we can do.

**Comment by Antreesy** [comment]
Current state:
![image](https://github.com/user-attachments/assets/114586ee-3f04-4104-94df-2405554cd2b1)

Actual discussion is in https://github.com/nextcloud-libraries/nextcloud-vue/issues/5951
